### ISSUE TITLE
Question: How can I retrieve parameters sent to the Bind-Route-Service API?

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/cloud_controller_ng#1080]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue
I run a command like `cf bind-route-service app_domain.com route_service_instance --hostname myhost -c '{"parameter": "value"}'`. The route service-route binding is successfully created. However, I do not find an API to retrieve the parameters from a corresponding Cloud Controller API.

## Context
While creating a route service binding is possible, is retrieval of parameters possible for the same binding? This is of course, possible for an application-service instance binding via the `/v2/service_bindings` API

## Steps to Reproduce
- Create a route-service-binding using `cf bind-route-service` and passing parameters via `-c`
- Check if an API exists to retrieve the parameters

## Expected result
A Cloud Controller API must be present to retrieve parameters for a route-service binding

## Current result
I do not find a corresponding fetch API

## Possible Fix
n/a

**Comment by Samze** [comment]
Hey @abh1kg, 

Actually at the moment the `-c '{"parameter": "value"}` information for application-to-instance bindings are not stored by cloud controller and not available on the API. These are just sent to the service broker in order to configure the instance/binding being created.

We are mid-way through an [epic](https://www.pivotaltracker.com/n/projects/2105761) to support this use case for application-to-instance bindings. This will only work for service-brokers that implement the newly [proposed endpoints](https://github.com/openservicebrokerapi/servicebroker/pull/333) in the OpenServiceBroker spec. This should be completed fairly soon.

We wanted to deal with the 90% case, application-to-instance bindings, before we added support for route-bindings too. 

Thanks for this feedback, just out of curiosity could you elaborate on your use case?

Thanks,
Sam & @ablease

**Comment by abh1kg** [comment]
@Samze : I dozed off a bit on this, apologies for that.
My wish is to enable proxying over Cloud Foundry routes to third-party endpoints, which reside in private network namespaces. I use the parameters currently to feed in the port for the third-party process. As you mention, I store this information in the service broker currently. If CC enables this, I need not store the port information for my use case any longer.

**Comment by Samze** [comment]
@abh1kg This has made it to our backlog https://www.pivotaltracker.com/story/show/155292930

**Comment by Samze** [comment]
@abh1kg Thanks for your patience! This has been added and made it into [CAPI 1.53.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.53.0).

Note that this requires that the service broker implements the newly added [fetching service binding](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#fetching-a-service-binding) endpoint to obtain the parameters.  If brokers support this feature then you can use this new [API](https://apidocs.cloudfoundry.org/2.0.0/service_instances/retrieve_a_particular_route_binding_parameters.html) in CC.
