### ISSUE TITLE
cloud_controller_clock job does not fail in case of database inconsistencies

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/cloud_controller_ng#1092]
## Issue

In case of persistent database inconsistencies the `cloud_controller_clock` job does not fail, e.g. `diego_sync` is not running anymore unnoticed.

## Context

We realized that the `diego_sync` job did not run for quite some time. When looking into the cc database, we saw that no scheduled jobs had run since weeks, i.e. the timestamps in table `clock_jobs` were very old. When comparing the database schema with another deployment, we saw that there was no primary key for that table. The following error was written into the `cloud_controller_clock` logs: `No primary key is associated with this model (Sequel::Error)`. Our assumption is that this was caused by a database restore.

## Steps to Reproduce

Manually delete the primary key for table `clock_jobs`.

## Expected result

The `cloud_controller_clock` job should fail, i.e. treat database inconsistencies as a fatal error.

## Current result

The following logs are written every 30 seconds:
* `SELECT * FROM "clock_jobs" WHERE ("name" = 'diego_sync') LIMIT 1 / log_level:info`
* `No primary key is associated with this model (Sequel::Error) / log_level:error`

The `cloud_controller_clock` job does not fail.

**Comment by lisamcho** [comment]
@philippthun, so you think that the backup/restore caused this system to be in this state? We don't see any code paths for the cloud_controller code to get into this state. The clock_jobs table was created with the primary key and the only migration altering it so far was to add one column.

We can't anticipate all database errors that might occur. We haven't run into a situation where the database was missing a primary key. If we were to fail the cloud_controller_clock job, then monit would restart it. Monitoring the following metrics will let you know about the health of this part of CloudFoundry:

- diego freshness (every time sync runs successfully this gets bumped)
- queued background jobs vs failed background jobs (this will let you monitor whether other jobs that the cloud_controller_clock schedules are being succesfully completed or not).

If you have an idea for how you'd handle this type of database error, we could consider a PR. Otherwise can you close this issue?

-Lisa and @ericpromislow

**Comment by selzoc** [comment]
@philippthun bumping this as it has been a week since we asked for more details.

-Chris

**Comment by philippthun** [comment]
@lisamcho We don't know for sure that this issue has been caused by a database restore - this is just a wild guess knowing that it was not caused by a program (we had also looked into the cc codebase) and assuming that it's very unlikely that someone deleted the primary key on purpose. We know for sure that database restores have been tested on this specific CF deployment and one of those tests was done in the timeframe when the jobs stopped working...

Even though monit would restart a failing cloud_controller_clock job it will eventually stop doing so and thus make this problem visible. As a corrupted database is a permanent error that the system cannot circumvent, a failing job seems to us to be the proper reaction.

Thanks for pointing out how to monitor these jobs. We've improved our monitoring/alerting and are confident to detect such a situation much faster in case it happens again.

**Comment by selzoc** [comment]
@philippthun OK if I close this issue then?  Seems like you've got a path forward?

-Chris

**Comment by philippthun** [comment]
@selzoc This particular incident has been resolved. But the intention of this bug report was to improve the behavior of cc in case of database inconsistencies. In case you disagree to failing the job in such a permanent error situation, feel free to close the bug.

**Comment by selzoc** [comment]
Hi @philippthun - thanks for the reminder, I misinterpreted an earlier comment.  We have opened a [story](https://www.pivotaltracker.com/story/show/156029607) for our PM @zrob to prioritize.

One thing of note - you can tell if this is happening by paying attention to the `bbs.Domain.cf-apps` and `bbs.Domain.cf-tasks` freshness metrics - if they are `1` it means that the `bbs` and `cloud_controller` are in sync, and if they are not emitted, that means the sync job has failed.  See [here](https://docs.cloudfoundry.org/running/all_metrics.html) for more details on the metric, and [here](https://docs.pivotal.io/pivotalcf/1-12/monitoring/kpi.html#cc-diego-sync) for guidance on what values you should look out for.

**Comment by charleshansen** [comment]
Story has been delivered and will hopefully be in the next release

**Comment by cwlbraa** [comment]
shipped in 1.71.0
