### ISSUE TITLE
CF Doc is outdated

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#1121]
## Issue
Latest documentation is notably outdated

## Context
The latest documentation for [v2](https://apidocs.cloudfoundry.org/280) is out of date - the latest version it lists is 280/2.99.0.

## Steps to Reproduce
Click link for [v2](https://apidocs.cloudfoundry.org/280).

## Expected result
Documentation should be current (something like 287/2.106.0?)

**Comment by chefhoobajoob** [comment]
+1

Cloud Foundry is continuing to advance because people want to take advantage of the new capabilities, and that can be impeded if the most current REST documentation is dated.

We were expecting the [CLI](https://github.com/cloudfoundry/cli) and the [java client](https://github.com/cloudfoundry/cf-java-client) to be current and in step with each other on container networking support, and spent probably more time than necessary trying to determine where the missing piece was.

**Comment by zrob** [comment]
thanks for the report.  they should be updated now and they link to cf-deployment
