### ISSUE TITLE
Emit metrics around blobstore latency

### ISSUE THREAD

**Issue by gowrisankar22** [cloudfoundry/cloud_controller_ng#1126]
Hello Colleagues,

Azure we are seeing droplet upload to blobstore is getting timed out due to the slowness of Azure storage. Currently, we don't have any mechanisms from CC to emit the blob store latency metrics. This will be really helpful in this kind of situations to the users to identify the latency problems on blob store on different iaas.

BRs, Gowrisankar

**Comment by zrob** [comment]
@selzoc this sounds similar to what we talked about earlier.  if you have some concrete thoughts on blobstore metrics, this could be a good place to record them

**Comment by tcdowney** [comment]
I think at a minimum we should time and emit metrics for the following in our wrapping Fog Client:
1. [download_from_blobstore](https://github.com/cloudfoundry/cloud_controller_ng/blob/2b359d2b7b7381fab2a61a78f8e932a81cbb28fd/lib/cloud_controller/blobstore/fog/fog_client.rb#L43)
1. [cp_to_blobstore](https://github.com/cloudfoundry/cloud_controller_ng/blob/2b359d2b7b7381fab2a61a78f8e932a81cbb28fd/lib/cloud_controller/blobstore/fog/fog_client.rb#L53)
1. Potentially [files_for](https://github.com/cloudfoundry/cloud_controller_ng/blob/2b359d2b7b7381fab2a61a78f8e932a81cbb28fd/lib/cloud_controller/blobstore/fog/fog_client.rb#L118)

Likewise for the WebDav client.

@selzoc probably has some other suggestions, but those three are the ones I'm usually curious about.

**Comment by zrob** [comment]
@petergtz @smoser-ibm

**Comment by smoser-ibm** [comment]
@tcdowney some of these we have in the bits service already - see http://cloudfoundry-incubator.github.io/bits-service/#metrics. 
However, latest version of bits-service is in GO and moved away from fog , but once bits is adopted you get some. Let me and @petergtz know what you think

**Comment by petergtz** [comment]
Note that out of the 3 metrics @tcdowney listed, Bits-Service only provides `cp_to_blobstore`. 

`download_from_blobstore` doesn't make sense in the Bits-Service, because we hand out redirects, so clients can download directly from S3, Azure, etc. Only uploads are funneled through Bits-Service.

`files_for` doesn't exist in the Bits-Service, it's all wrapped in the `delete` method, which it is used for in the Cloud Controller as well. Since we emit response time metrics for all our requests, it's more or less handled by that.

And to avoid confusion: our Go implementation emits a superset of metrics the Ruby implementation emits.

**Comment by charleshansen** [comment]
Looks like we should start with fog metrics for download_from_blobstore and cp_to_blobstore. For simplicity, we should emit the metric on every request, like routing latency (under https://docs.cloudfoundry.org/running/all_metrics.html#gorouter).

**Comment by sannidhi** [comment]
We are not emitting the metrics but users can use [this](https://github.com/cloudfoundry/capi-release/blob/develop/docs/blobstore-benchmarking.md) to run this script to get blobstore performance benchmark results. Closing this issue for now, please re-open if needed. Thanks!
