### ISSUE TITLE
Call to /spaces/{guid}/auditors returns invalid "spaces_url" response value

### ISSUE THREAD

**Issue by ChristmasTaco** [cloudfoundry/cloud_controller_ng#1162]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

When performing a GET to the CCAPI to return space auditor details, the value returned in the "spaces_url" key is invalid. I believe that to be true because when executing a GET to the URL returned in that key, I am given a 'no results' response.

## Steps to Reproduce

1) Perform a GET to:

https://{foundation URL}/v2/spaces/{GUID}/auditors

2) From response, grab the URL value in the "spaces_url" key

3) Perform a GET to that URL value, which yields a 'no results' response, example below:

{
	"total_results": 0,
	"total_pages": 1,
	"prev_url": null,
	"next_url": null,
	"resources": [
	]
}

## Expected result

I would have expected a response including a JSON payload with content, given the URL was returned by another endpoint as a valid value.

## Current result

Currently, the response is a no-results:

{
	"total_results": 0,
	"total_pages": 1,
	"prev_url": null,
	"next_url": null,
	"resources": [
	]
}

**Comment by ericpromislow** [comment]
Hi @ChristmasTaco 

The URL is actually valid, but not the one you wanted. Because in this case the first URL was /v2/spaces/{GUID}/auditors , the inverse URL is
/v2/users/{USERGUID}/audited_spaces

The URL /v2/users/{GUID}/spaces
returns the list of all the spaces where that user is a SpaceDeveloper

Hope this helps

Eric Promislow - CAPI Community Support
