### ISSUE TITLE
if a user delete itself by `cf delete-user <user> -f`,  some orphan record will be left on ccdb.

### ISSUE THREAD

**Issue by Xiaohua-Shen** [cloudfoundry/cloud_controller_ng#1217]
## Issue

if a user delete itself by `cf delete-user <user> -f`,  some orphan record will be left on ccdb.

## Steps to Reproduce

given user `admin`  as example:
1. cf login
2. cf delete-user admin -f

## Expected result

All this user related user records should be deleted both from uaadb and ccdb. 

## Current result

but now ccdb remain this user's record in ccdb.user table.

Before delete:
cc db's user table:

```
ccdb=> select * from users;
 id |                 guid                 |         created_at         |         updated_at         | default_space_id | admin | active 
----+--------------------------------------+----------------------------+----------------------------+------------------+-------+--------
  1 | 3f325918-3f33-4c2f-ae5e-d39729e34d98 | 2018-09-17 07:58:11.401389 | 2018-09-17 07:58:11.401389 |                  | f     | t
  2 | elkadapter                           | 2018-09-17 07:58:13.31649  | 2018-09-17 07:58:13.31649  |                  | f     | t
  3 | 903521db-fbef-42d4-b548-3da34349753c | 2018-09-17 07:58:58.736426 | 2018-09-17 07:58:58.736426 |                  | f     | f
```
here 3f325918-3f33-4c2f-ae5e-d39729e34d98 is admin.

after run `cf delete-user admin -f`,
cc db's user table:
```
ccdb=> select * from users;
 id |                 guid                 |         created_at         |         updated_at         | default_space_id | admin | active 
----+--------------------------------------+----------------------------+----------------------------+------------------+-------+--------
  2 | elkadapter                           | 2018-09-17 07:58:13.31649  | 2018-09-17 07:58:13.31649  |                  | f     | t
  3 | 903521db-fbef-42d4-b548-3da34349753c | 2018-09-17 07:58:58.736426 | 2018-09-17 07:58:58.736426 |                  | f     | f
  4 | 3f325918-3f33-4c2f-ae5e-d39729e34d98 | 2018-09-17 13:23:18.065014 | 2018-09-17 13:23:18.065014 |                  | f     | t
```
seems related record is deleted (id=1) and has been added back as a new user record (id=4).

## Possible Fix

above id=4 record should be deleted too.

**Comment by iredelmeier** [comment]
@ericpromislow and I reproduced this.

However, we're not sure that it is a real bug, since the user is successfully deleted from (and not re-inserted into) UAA's DB, and therefore won't have any of the scopes necessary to use CC.

The main exception is when the user still has a valid token, as they can continue to use the token to interact with the CC until the token expires. (This is also the main scenario in which the user will be re-inserted into CC's DB.) The severity of this situation depends on the token's TTL. Note that this is a common problem with JWTs in general - not something CC/CF-specific.
