### ISSUE TITLE
[Feature Request]: Grace period per app

### ISSUE THREAD

**Issue by saescha** [cloudfoundry/cloud_controller_ng#1289]
Hi folks,

I have an app that possibly needs more than 10 seconds to process request(long-runner can take up to 30 seconds). I found no way to process these long-running requests fail-save ( For example a Diego Drain could trigger a container shutdown and the grace period is to short, to finish the inflight requests, ending up with 502 )

A clean option for me would be, if it would be possible to give my specific app a grace period of 30 seconds. As far as I understood, there would be no downside, if my app terminates after all inflight requests are complete ( most of the time the shutdown would take less than 10 seconds ).

Is there a way to tell Diego an app specific grace period?

Thanks & Regards,
Sascha Zilli

**Comment by heyjcollins** [comment]
cc @heyjcollins

**Comment by berndgoetz** [comment]
Not much happening on this end, it seems. 

Kubernetes knows the terminationGracePeriodSeconds parameter, more details at
https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace. How about adding this to CF?

**Comment by heyjcollins** [comment]
Thanks @berndgoetz - we're evaluating the termination grace period in CF currently and, if we decide to proceed with a change, will share out our proposal/options with the community in the next month or so.

**Comment by cwlbraa** [comment]
This is bosh-configurable on the rep. I'd really rather only offer this configuration to the operator because we like to try to keep evacuation and cell deploys below the platform's line of abstraction. If developers decide they want longer grace periods for their apps, one app with many instances can slow down cell deploys to whatever speed it decides and that will make it harder for operators to update the underlying cells. 

https://github.com/cloudfoundry/diego-release/blob/develop/jobs/rep/spec
```
  containers.graceful_shutdown_interval_in_seconds:
    description: "EXPERIMENTAL: time in seconds between signalling a container to shutdown gracefully and stopping it forcefully. Should not be less than 10."
    default: 10
```

**Comment by heyjcollins** [comment]
@cwlbraa - thanks for bringing this up. I didn't make it clear that I'm the PM on Diego, responsible for the rep and I share your concerns.

**Comment by imdurgadas** [comment]
@heyjcollins , 10 seconds grace period is too low and one should be able to set a appropriate limit based on the app functioning.
Kubernetes also provides it and it's a must considering async jobs in place.

**Comment by sethboyles** [comment]
We are marking this issue as "wontfix" due to its age and complexity, and due to the fact that this is configurable on a foundation level.  AFAIK Diego [doesn't offer a way for us to configure this](https://pkg.go.dev/code.cloudfoundry.org/bbs/models#DesiredLRP), so we would have to do quite a bit of work to implement this.  

We're not entirely against it, but it hasn't been requested enough to merit us tackling it.  If we get more requests and feedback around this feature, we are willing to reevaluate.

**Comment by JenGoldstrich** [comment]
Hey @saescha, 

Given the "wont fix" label and the comment above, @sethboyles and I are going to close this issue.

Please anyone who wants this re-opened feel free to comment below with more details and we will re-evaluate our decision
