### ISSUE TITLE
POST /v3/apps/:app_guid/tasks does not ignore null values for the parameters

### ISSUE THREAD

**Issue by enchobelezirev** [cloudfoundry/cloud_controller_ng#1308]
## Issue

When executing the following request: POST /v3/apps/:app_guid/tasks with memory_in_mb: null and disk_in_mb: null as body, the CF Controller returns 500 Internal Server Error.

## Context

Before, the request with the null values in the Body was successful. Now, the calls are failing with the error mentioned above.

## Steps to Reproduce

Create a POST request to /v3/apps/:app_guid/tasks with the following body as json:
{
  "command": "echo test",
  "disk_in_mb": null,
  "memory_in_mb": null,
  "name": "testing"
}
 
## Expected result

No failure. Ignore the parameters which are null and process the request. Before, these requests were passed without problems

## Current result

Failure with 500 Internal Server Error without any  cause what is the issue

## Possible Fix

Ignore the null values and process the other parameters

**Comment by tcdowney** [comment]
Thanks for reporting this @enchobelezirev! 

Looks like we introduced this regression when we added the ability to [create tasks](http://v3-apidocs.cloudfoundry.org/version/3.68.0/index.html#create-a-task) using a [Process](http://v3-apidocs.cloudfoundry.org/version/3.68.0/index.html#the-process-object) as a template. This is fixed in 453c25e4573936cedc2a5a8bd5f73d06f5ed5755 and will ship in the next capi-release.

**Comment by enchobelezirev** [comment]
Thanks a lot!
