### ISSUE TITLE
Inappropriate status code for /v3/spaces when unauthorized

### ISSUE THREAD

**Issue by wapacro** [cloudfoundry/cloud_controller_ng#1313]
## Issue
Calling the `/spaces` endpoint of the V3 API with a space GUID that the user associated with the access token isn't permitted to retrieve returns `HTTP 404 - Not Found` (CF-ResourceNotFound) instead of `HTTP 403 - Forbidden` (CF-NotAuthorized) like it used to in V2.

## Steps to Reproduce
1. Create a space and make sure only `User A` has permission to see/get details about it.
2. Get an access token for the CF API as a different User (i. e. `User B`)
3. Request `/v3/spaces/:id` with the space GUID of Step 1 and the access token of Step 2.

## Expected result
The response should be `HTTP 403 - Forbidden` with CF-NotAuthorized as error title.

## Current result
The response is `HTTP 404 - Not Found` with CF-ResourceNotFound as error title.

## Possible Fix
The `/v3/spaces/:id` endpoint should behave the same way as `V2` did and return the appropriate `403` status code.

**Comment by tcdowney** [comment]
This is intentional.

The v2 APIs can be inconsistent in this behavior, but in general the v3 APIs will prefer returning a 404 over a 403 for authenticated (but unauthorized to read the resource) users to avoid leaking information about the existence of said resource.

We're following this bit of [the spec](https://httpstatuses.com/403):
> An origin server that wishes to "hide" the current existence of a forbidden target resource MAY instead respond with a status code of 404 Not Found.

**Comment by wapacro** [comment]
Thanks for the clarification.
