### ISSUE TITLE
bulk audit event deletion causes high database latency

### ISSUE THREAD

**Issue by sjolicoeur** [cloudfoundry/cloud_controller_ng#1339]
## Issue

We've (MySQL Team)  seen in environments where a large number of events are deleted a stop the world effect on the database. This is due to the bulk deletion of events by the `events_cleanup` job [1]. 

[1] https://github.com/cloudfoundry/cloud_controller_ng/blob/65a75e6c97f49756df96e437e253f033415b2db1/app/jobs/runtime/events_cleanup.rb
[provide quick introduction so this issue can be triaged]

## Context

Galera clusters will stop the world for large transactions. And a bulk delete of ~200K rows will cause the database to manifest hiccups in service. 

## Steps to Reproduce

Ona high volume installation of CF, deleting around 200K rows in the events table at a time will cause some pauses in different applications using the central MySQL cluster.

## Expected result

We would like to see deletion done in smaller batches.

## Current result

Ask the MySQL Team.

## Possible Fix

Perform the deletion in batches. One could paginate over the result set and perform the deletion on a page by page basis. 

ping: @abg

**Comment by tcdowney** [comment]
Your proposal to do the deletion in batches of ~1000 (@sjolicoeur @abg do you as Galera/Percona experts have a recommendation here?) makes a lot of sense to me. We have similar batching patterns in place for our Diego Sync job and database encryption key rotator. See:

* https://github.com/cloudfoundry/cloud_controller_ng/blob/8696679cd73ca795d15fc32a1b9a10b68fb164f8/lib/cloud_controller/diego/processes_sync.rb#L102-L112
* https://github.com/cloudfoundry/cloud_controller_ng/blob/65a75e6c97f49756df96e437e253f033415b2db1/lib/cloud_controller/errands/rotate_database_key.rb#L21-L27

**Comment by tcdowney** [comment]
I don't think any of our other tables typically get close to the size of the `events` table, but some other cleanup jobs could probably benefit from this as well are:

* [Completed Tasks cleanup](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/runtime/prune_completed_tasks.rb)
* [Usage events](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/runtime/app_usage_events_cleanup.rb)
* And probably more of these [scheduled cleanup jobs](https://github.com/cloudfoundry/cloud_controller_ng/blob/8696679cd73ca795d15fc32a1b9a10b68fb164f8/lib/cloud_controller/clock/scheduler.rb#L8-L21)

**Comment by tcdowney** [comment]
We addressed this issue in https://github.com/cloudfoundry/cloud_controller_ng/commit/2430581f1078e6c130b194e67df2762203d9b5ba, not sure why Github didn't auto link that commit to this. 🤔

**Comment by tcdowney** [comment]
@sjolicoeur @aaronshurley 

This change is in capi-release [1.81.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.81.0), let us know if you see improvements in your environments.

**Comment by abg** [comment]
We've seen mixed result from this change.  The "stop the world" effect we previously observed under Galera clusters has disappeared which has been a great improvement.   However, this has been replaced by a large spike in read operations in the storage engine over a few hour window:

 ![innodb_rw_s](https://user-images.githubusercontent.com/163206/59284068-3e6b0d00-8c31-11e9-8c3f-0cfad4c53948.png)

Digging into this a bit, we see the chunking query is not executed efficiently by MySQL.   The current implementation constructs a query of the form:

```
DELETE FROM `events` WHERE (`id` IN (SELECT * FROM (SELECT `id` FROM `events` WHERE (created_at < '2019-03-10 20:00:00') LIMIT 1000) AS `t1`));
```

From the mysql slow query log it is obvious this query is doing a full table scan:

<pre>
# Query_time: 60.012630 Lock_time: 0.000076 Rows_sent: 0 <b>Rows_examined: 20913373</b> Rows_affected: 1000
DELETE FROM events WHERE (id IN (SELECT * FROM (SELECT id FROM events WHERE (created_at < '2019-03-10 20:00:00') LIMIT 1000) AS t1));
</pre>

For this environment, there are a few hundred thousand events to cleanup daily, so this gets run a few hundred times over the course of ~3 hours.   The event cleanup process is essentially monopolizing a full CPU core during this time and thrashes the InnoDB buffer pool needlessly.

**Recommendations**

The load from the current implementation can cause problems in some environments.

There are a few ways to rewrite this query to obtain a more efficient access pattern.  The most obvious would be the simple `DELETE ... LIMIT` form that MySQL supports:

```
DELETE FROM events WHERE (created_at < '2019-03-10 20:00:00') LIMIT 1000
```

MySQL is able to use an index scan in this case and efficiently finds the chunk of rows to delete.  This form is MySQL specific and not generalizable to other databases.   Postgres works fine with the current form.

Alternatively a small tweak to the current query can result in a much improved query plan:

<pre>
DELETE events <b>FROM events</b> WHERE (id IN (SELECT * FROM (SELECT id FROM events WHERE (created_at < '2019-03-10 20:00:00') LIMIT 1000) AS t1))
</pre>

This form uses a MySQL [multiple-table delete trick](https://mysqlserverteam.com/multi-table-trick/) to kick the MySQL optimizer into generating a better access plan.

Either of these forms execute in dozens of milliseconds rather than ~60s per chunk.

**Comment by tcdowney** [comment]
Thanks for the followup @abg, sounds like we're not done here so I created a new issue (https://github.com/cloudfoundry/cloud_controller_ng/issues/1373) to make this is easier for our team to track since this change has already been accepted/out in the past few releases. Would you mind chatting with us more about it on that one?
