### ISSUE TITLE
Unsupported fetching of service instance/binding parameters returns 400 Bad Request

### ISSUE THREAD

**Issue by nictas** [cloudfoundry/cloud_controller_ng#1344]
## Issue

`GET /v2/service_bindings/<GUID>/parameters` and `GET /v2/service_instances/<GUID>/parameters` both return `400 Bad Request` when the operation is not supported. 4xx errors are generally used when the client can do something in order to make the request possible. In these cases, however, it's actually the service broker that doesn't support the feature (right?), so maybe the correct HTTP code would be `502 Bad Gateway` (just as it is for other service broker related failures)?

## Context

We're developing a tool that automates operations for service instances (create/update/delete/bind etc.) and we're using the `/v2/service_bindings/<GUID>/parameters` and `/v2/service_instances/<GUID>/parameters` endpoints in order to check whether a service's credentials need to be updated. We noticed in Dynatrace that our requests fail with `400 Bad Request` and we couldn't see the actual responses, so we initially assumed that there's something wrong with our requests. Of course, reproducing the errors was easy, so it didn't take us long to figure out that the `400` status codes actually mean "this feature is not supported".

## Steps to Reproduce

Call `GET /v2/service_bindings/<GUID>/parameters` and `GET /v2/service_instances/<GUID>/parameters` for a service that doesn't support the retrieval of instance and binding parameters.

## Expected result

`502 Bad Gateway` is the response we've gotten used to with errors related to service brokers. It would make sense, considering that 5xx errors generally mean that the client can't do anything about the failure.

**Comment by blgm** [comment]
Hi @nictas, thank you for raising this issue.

When this feature was originally implemented, there was some discussion about which HTTP status code to use.  The implementers chose HTTP 400 in order to be consistent with behaviours from other endpoints.  You can read the discussion here: https://www.pivotaltracker.com/n/projects/2105761/stories/150801660/comments/185413596

I think you have a very good point that HTTP 400 is not the ideal code for this situation.  The people who implemented it seemed to think the same, but decided it was a better trade-off to be consistent with other endpoints as this makes it easier to write clients.

Our suggestion would be that we try and do better with the `v3` API and leave the `v2` API as it is.  What do you think of this suggestion?

Best wishes, @georgi-lozev and George

**Comment by nictas** [comment]
Aaah, this makes sense now! Thanks for the info!

And yes, I think that what you suggested is the correct approach.

**Comment by georgi-lozev** [comment]
@nictas, another thing to have in mind when designing your automation tools is that there is currently initiative for migrating all `v2` endpoints to `v3`. The goal of it will be at the end to deprecated `v2` entirely and you may even see some deprecation warning messages in the docs today https://apidocs.cloudfoundry.org/9.0.0/#apps.

I don't think you have to do anything immediately in that regard, but it's something that could expect in future and prepare your automation with good abstractions to handle it.
