### ISSUE TITLE
disk_quota incorrectly blocked using v3-apply-manifest

### ISSUE THREAD

**Issue by bengerman13** [cloudfoundry/cloud_controller_ng#1405]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
NOTE: We have a custom disk_quota set to 4096 MB.

using `cf push`, I can push an app with this manifest specifying a disk_quota of 4096 MB:
```yaml
---
applications:
- name: test-python-flask
  random-route: true
  buildpacks:
    - python_buildpack
  memory: 256M
  disk_quota: 4096MB

````
Using `cf v3-apply-manifest -f ./manifest.yml`, I get the error `disk_quota too much disk requested (requested 4096 MB - must be less than 2048 MB)`

**What happened**
I get the error `disk_quota too much disk requested (requested 4096 MB - must be less than 2048 MB)`

**Expected behavior**
I should be able to use the full disk quota allowed

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Have an environment with a custom `maximum_app_disk_in_mb`, higher than 2048MB
2. use cf v3-apply-manifest with a manifest requesting more than 2048MB, but less than `maximum_app_disk_in_mb` disk quota
3. See error

**Provide more context**
- Mac OS X 10.14 iTerm
- `cf version 6.46.0+29d6257f1.2019-07-09`
- 2.138.0

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by bengerman13** [comment]
Is there any update on this issue?

**Comment by cwlbraa** [comment]
thanks for bumping! @ssisil & @ankitjain1988 & @selzoc this seems like a scheduleable one, no?

**Comment by selzoc** [comment]
scheduled

**Comment by bengerman13** [comment]
Thanks for taking a look, @cwlbraa and @selzoc !

**Comment by reneighbor** [comment]
Hi @bengerman13,

Thanks for writing, and thank you for your patience. @piyalibanerjee and I were able to take a look at this today and replicated the issue with `cf v3-apply-manifest` not recognizing the `maximum_app_disk_in_mb ` property that you updated on api instances.

The reason why this was happening is because applying a manifest happens on an async job executed by a cloud_controller_worker. Therefore you need to make sure that the `maximum_app_disk_in_mb` configuration is on your `cloud_controller_worker` jobs (as well as `cloud_controller_ng` jobs, to make sure that synchronous and async application updates have the same config values).

If you're using the topology found in cf-deployment, the following ops file should work. (We just gave it a try and confirmed that it fixed the issue when we replicated it).

```
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/maximum_app_disk_in_mb?
  value: 4096
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/maximum_app_disk_in_mb?
  value: 4096
```

Please let us know if you run into any further problems,
Piyali and Renee

**Comment by bengerman13** [comment]
Thanks @reneighbor - we'll give it a try!

**Comment by cwlbraa** [comment]
@bengerman13 did this work for you?

**Comment by cwlbraa** [comment]
I'm gonna assume this worked for you because the other issue was closed :)
