### ISSUE TITLE
v3: Make it easier to get all route-destinations

### ISSUE THREAD

**Issue by robachmann** [cloudfoundry/cloud_controller_ng#1449]
## Issue

Extract `/v3/routes/:guid/destinations` to dedicated endpoint and support pagination.

## Context

To get a list of all routes and their app_guid-mappings (destinations), I need to query all routes `/v3/routes` and for each route, execute a call to `/v3/routes/:guid/destinations`.

In a large CF deployment with 14000 routes, this takes 3 requests to query all routes (with page-size 5000) and another 14000 requests to get the destinations for each route.

## Steps to Reproduce

cf curl /v3/routes (https://v3-apidocs.cloudfoundry.org/version/3.74.0/index.html#list-routes)
cf curl /v3/routes/:guid/destinations (https://v3-apidocs.cloudfoundry.org/version/3.74.0/index.html#list-destinations-for-a-route)

I'm interested in the app's `guid` of each destination.

```
  {
    "destinations": [
      {
        "guid": "89323d4e-2e84-43e7-83e9-adbf50a20c0e",
        "app": {
          "guid": "1cb006ee-fb05-47e1-b541-c34179ddc446",     <-- 
          "process": {
            "type": "web"
          }
        },
        "weight": null
      }
    ],
    "links": {
      "self": {
        "href": "https://api.example.org/v3/routes/cbad697f-cac1-48f4-9017-ac08f39dfb31/destinations"
      },
      "route": {
        "href": "https://api.example.org/v3/routes/cbad697f-cac1-48f4-9017-ac08f39dfb31"
      }
    }
  }
```

## Expected result

Ideally, all destinations could be queried with only a couple of requests.

## Current result

As described, this takes more than 14000 requests. 

## Possible Fix

I see two possibilities to optimise these calls:
1. Include the app-guid in the `route` object. This does not make a lot of sense in the current data model. 
2. Promote route-destinations to top-level entities, like `service_bindings` (https://v3-apidocs.cloudfoundry.org/version/3.74.0/index.html#list-service-bindings). A possible structure could look like this:
```
"relationships": {
      "app": {
        "data": {
          "guid": "74f7c078-0934-470f-9883-4fddss5b8f13"
        }
      },
      "route": {
        "data": {
          "guid": "8bfe4c1b-9e18-45b1-83be-124163f31f9e"
        }
      }
    } ...
```
I would expect proper pagination from such a top-level entity. Thus, getting all destinations would need only a couple of requests. 

Thank you very much for consideration.

**Comment by cwlbraa** [comment]
@Gerg any thoughts on `/v3/route_destinations`? Sounds like a reasonable request to me.

**Comment by tcdowney** [comment]
@gerg why are Destinations separate from their Route to begin with? Were we worried about 1 Route with tons of Destinations and no way to paginate them?

On the CF Networking team we're working on revamping the routing tier for CF on Kubernetes and will be creating Route CRDs that look like this (working draft):
https://github.com/cloudfoundry/cf-k8s-networking/blob/master/cfroutesync/config/route.yaml

We're building a component that calls out to v3 endpoints on Cloud Controller and syncs these routes en masse. We have the same problem as this issue and would like something better as well. 🙂

`/v3/route_destinations` could work. Would be nice to have `route_guid` exposed better than just in the link though because that's not fun for clients to parse. Would also like an `include=route` because we don't just want the Destinations in isolation -- they need to be aggregated under a Route (see the CRD above).

**Comment by Gerg** [comment]
@tcdowney Yea, mostly just worried about large response payloads. We're considering adding in destinations to the main response body or something like `GET /v3/routes?includes=destinations` or `GET /v3/routes?fields=destinations`

**Comment by robachmann** [comment]
While I appreciate the thoughts and considerations, looking at the existing v3 implementation shows that all resources except `/v3/apps` are using query-parameters solely for filtering (and pagination). Therefore, I would prefer to stick to that and include destinations either in the _main response body_ or move them (as ordinary n:n data) to different tree. Adding a query-param to include destinations is my least favored solution.

**Comment by tcdowney** [comment]
@robachmann the concept of an `include` parameter actually is something that's in the V3 API today in more than just apps:

* https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#include (concept)
* https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#list-spaces (example endpoint)

The responses end up looking like this (including orgs and spaces for apps):

```

   "pagination": {
      "total_results": 2
      // rest of pagination omitted
   },
   "resources": [
      {
         "guid": "42ad8d5a-8124-4fc7-baf2-3f39bfe1c170",
         "name": "app1"
         // rest omitted
      },
      {
         "guid": "b90f287b-fcdd-4cbb-9523-1a8dbd2a9837",
         "name": "app2"
         // rest omitted
      }
   ],
   "included": {
      "spaces": [
         {
            "guid": "134f95ad-b5eb-4b55-9ce0-b906c513d54b",
            "name": "space1"
            // rest of info on space1 omitted
         },
         {
            "guid": "00b76d5c-5176-4cbc-be5d-0bd76363dca9",
            "name": "space2"
            // rest of info on space2 omitted
         }
      ],
      "organizations": [
         {
            "guid": "b2075a71-28b6-411a-a896-56f75d892f58",
            "name": "org1"
            // rest of info on org1 omitted
         },
         {
            "guid": "b56fbd01-296b-442b-8faf-a559aebf985e",
            "name": "org2"
            // rest of info on org2 omitted
         }
      ]
   }
}
```

**Comment by robachmann** [comment]
You're right, I confused it with `spaces` where I saw this first :-)

**Comment by Gerg** [comment]
Destinations, as they currently exist, are basically [pseudo-resources](https://github.com/cloudfoundry/cc-api-v3-style-guide#pseudo-resources). 

Like other pseudo-resources, I don't think `include` is a good option because there is no easy way to link the destinations back to their routes (since destinations don't have route guids). The proposed [fields](https://github.com/cloudfoundry/cc-api-v3-style-guide#proposal-requesting-specific-fields-resources) parameter could be a useful tool for embedding pseudo-resources into their parent resource.

Otherwise, we could just include destinations in the regular responses. There is some prior art for resources with potentially giant fields (I'm looking at you ASGs).
