### ISSUE TITLE
No asynchronous orphan mitigation when saving to the database during instance creation fails

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/cloud_controller_ng#1687]
## Issue

According to the [Open Service Broker API Specification](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md), section [Orphan Mitigation](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#orphan-mitigation), "the Platform SHOULD attempt to delete resources it cannot be sure were successfully created, and SHOULD keep trying to delete them until the Service Broker responds with a success."

In case cloud controller fails to save to the database **after** sending a provision request to the service broker, only a single synchronous orphan mitigation is attempted. If this attempt fails, the service instance remains forever.

## Context

When creating two service instances with the same name in parallel, cloud controller issues two provision requests to the service broker. But saving to the database succeeds only for one instance, for the other one the following error is written to the logs:
```
Failed to save while creating service instance <guid> with exception: name unique.
```

Cloud controller then tries to delete the other instance:
```
Attempting synchronous orphan mitigation for service instance <guid>
```

But in case synchronous deprovisioning of the orphaned service instance fails, cloud controller does not re-try deletion asynchronously as recommended by the specification mentioned above.

Here is the cloud controller code that tries to cleanup the resource: https://github.com/cloudfoundry/cloud_controller_ng/blob/e53ed670640fd61ab0a9a079dc4b42d0d253d57c/app/actions/services/service_instance_create.rb#L57-L62

## Steps to Reproduce

Looking at the source code of class [ServiceInstanceCreate](https://github.com/cloudfoundry/cloud_controller_ng/blob/e53ed670640fd61ab0a9a079dc4b42d0d253d57c/app/actions/services/service_instance_create.rb) shows that now asynchronous job is created when saving to the database fails.

## Expected result

According to the specification mentioned above the recommendation is to "keep trying to delete" the service instance "until the Service Broker responds with a success."

## Current result

The service instance remains an orphan...

## Possible Fix

Setup an asynchronous job in case synchronous deprovisioning fails.

**Comment by kirederik** [comment]
Hi @philippthun,

Thanks for raising this issue.

If we understood it correctly, there are two issues:
(1) If you try and create two SIs with the same name, then two provision requests are sent to the broker
(2) If a provision fails, only one attempt is made at orphan mitigation rather than continuing forever as the OSBAPI spec says a platform should

Problem (1) can no longer occur on v3 because the provision is sent after the SI is saved to the DB. Whereas in V2 is was the other way around.

However, problem (2) still persists: CC will still make a single attempt at orphan mitigation, and the spec says we should try forever. We are unsure if its a real bug or a intentional implementation by the past team.

Either way, it sounds like something we should fix to be respecting the spec. First, we'd like like to understand what are the consequences/impact of (perhaps) having dozens of jobs in a never ending loop, since there's no guarantee that the next deprovision request would be accepted.

We'll investigate that and think about some mechanism to stop the job of being reenqueued. We are currently implementing the final bits of the v3 service instances endpoints and will come back to this later. 

How does that sound?

Thanks!

**Comment by blgm** [comment]
@philippthun, the `POST /v3/service_instances` endpoint saves the service instance in the database before asking the service broker to create it. This means that should someone try to create two service instances with the same name in parallel, then only one of those commands would result in a request to the broker and there would be no need for orphan mitigation.

There is no plan to fix this for the `POST /v2/service_instances` endpoint where the problem was originally reported, as this would require a significant re-write.
