### ISSUE TITLE
Cannot update service instance metadata while there's an ongoing operation for it

### ISSUE THREAD

**Issue by nictas** [cloudfoundry/cloud_controller_ng#1781]
## Issue

Since [CAPI 1.96.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.96.0) a service instance's metadata can no longer be updated while there's an ongoing asynchronous operation for it. The easiest way to reproduce this issue is to use a service broker that supports asynchronous creation of service instances:
```
cf create-service <OFFERING> <PLAN> <NAME>
```
Then, immediately afterwards try to update the metadata. I'll post an example with the CF Java client, since that's what I'm using, but `cf curl` should work just as well:
```
CloudFoundryClient client = ReactorCloudFoundryClient.builder()...
client.serviceInstancesV3()
      .update(UpdateServiceInstanceRequest.builder()
                                          .serviceInstanceId(<GUID>)
                                          .metadata(<METADATA>)
                                          .build())
      .block();
```
This results in:
```
CF-AsyncServiceInstanceOperationInProgress(60016): An operation for service instance <NAME> is in progress.
```

## Context

According to the CF V3 API specification (see [here](https://v3-apidocs.cloudfoundry.org/version/3.87.0/index.html#update-a-service-instance)):

> Some [service instance] updates can be performed entirely within the Cloud Controller in which case the response is synchronous. Some updates require communication with the service broker, in which case the response will be asynchronous. The response will be asynchronous if:
> 
> * `parameters` are specified
> * `service_plan` is specified
> * `maintenance_info` is specified
> * `name` is specified and the service offering has the `allow_context_updates` feature enabled

If I understand this correctly, metadata updates are not communicated to the service broker. It's therefore strange that the update would be rejected because of an ongoing operation for that service instance.

Was this an intended change or a regression of some sort?

**Comment by FelisiaM** [comment]
Hi @nictas 

Thanks for reaching out.

It is true that an update of only the metadata of the service instance does not trigger a broker operation, as documented, however, the update operation cannot be done while another operation on the SI is ongoing.
This is the intended behaviour of the v3 API and you can see it now since we are enhancing and completing the v3 API. We think that it might be risky to allow several operations to occur on the same SI while we are not sure that it has completed creation. 

I am not sure of your use case, but I can suggest you use the [v3 create service instance](http://v3-apidocs.cloudfoundry.org/version/3.87.0/index.html#create-a-service-instance) endpoint that allows you to specify the metadata on the time of sending the create request. 

Thanks,
Felisia

**Comment by nictas** [comment]
Thanks @FelisiaM! I just wanted to make sure that this was an intended change.
