### ISSUE TITLE
cf v3-push APP fails over long distance WAN (Client in India to U.S Azure DC)

### ISSUE THREAD

**Issue by pivotal-wesley-robertson** [cloudfoundry/cloud_controller_ng#1906]
In trying to push an app from a location in India to a US Datacenter. I found that when using cf v3-push, the app push would fail with a 502. Doing a normal cf push however worked perfectly. 

IaaS is Azure:
```
RESPONSE: [2020-09-15T19:21:54+05:30]
HTTP/1.1 502 Bad Gateway
Content-Length: 67
Content-Type: text/plain; charset=utf-8
Date: Tue, 15 Sep 2020 13:51:54 GMT
X-Cf-Routererror: endpoint_failure
X-Content-Type-Options: nosniff
502


Unexpected Response
Response Code: 502
Code: 0, Title: , Detail: 502 Bad Gateway: Registered endpoint failed to handle the request.
```

The reasoning for using v3 was the customer needed a sidecar for their app. Nonetheless, the app was able to successfully deploy when the client is in the United States using cf v3-push. This confirmed a timeout on the customers loadbalancer which is perfectly understandable. 

My concern however, is if the customer does upgrade to PAS 2.10.5 the v7 cf CLI will become default. I expect that this same behavior, failing on cf push in India, will produce the 502s on the default cli. 
As I understand it, there is more communication built into the v3 api which is causing the delay?

To reproduce, perform a v3 push from extremely long distance over WAN. 

I would expect it to work as with cf push and start the app. It must be because v7 push breaks up the push into individual API calls, while v2 would just make one call to capi and have CAPI handle the rest.

**Comment by Gerg** [comment]
Hey @pivotal-wesley-robertson,

What request is timing out? If it's uploading the app bits (package), then it could be because the v6 CLI's `v3-push` command doesn't support resource matching and thus must upload significantly larger files. The v7 CLI's `push` command does support resource matching, so this won't be an issue when they upgrade.

If they are only interested in adding a sidecar to the application, then they can use the v6 CLI's `v3-apply-manifest` command to apply the manifest without uploading new app bits.

Thanks,
Greg

**Comment by Gerg** [comment]
I'm going to close this issue since there hasn't been any recent activity. Feel free to re-open if the above steps don't resolve the issue. Thanks!
