### ISSUE TITLE
Allow operators to specify the CPU request weight

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/cloud_controller_ng#2107]
## Issue

Operators should have the ability to customize the weight of the CPU requests calculation similar to what they can do in Diego. 

## Context

Currently we find the CPU requests to be too heavy. We are seeing CPU requests 10x our utilization in our cluster. We would like to be able to configure this weight either on a per app basis or globally. I believe the calculation is done [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/951eb7c60d9fcbcfc7171df4d92d0b4abb8cf52f/lib/cloud_controller/diego/task_cpu_weight_calculator.rb#L12-L17)

Related issue on cf-for-k8s project: https://github.com/cloudfoundry/cf-for-k8s/issues/608

**Comment by sethboyles** [comment]
@braunsonm I think the crux of this issue is Eirini is using a value that is intended for [relative balancing](https://github.com/cloudfoundry/bbs/blob/7b6fa295fa8d7a5e4b280e1b822ac52fe581a36f/doc/defining-tasks.md#cpuweight-optional) to estimate absolute limits instead.  

This does not seem like a great long-term solution given how differently Diego and Eirini/K8s treat these weights.  Not sure what the ideal solution is here, but we will discuss with cf-for-k8s team.

**Comment by braunsonm** [comment]
Thanks @sethboyles Looking forward to your response. I would agree and would prefer a more long term solution of having this configured on a per-app basis. However I was told this would take a lot more time since it would require changes to the app manifest spec.

**Comment by sethboyles** [comment]
closing in favor of https://www.pivotaltracker.com/n/projects/2172361/stories/177225389
