### ISSUE TITLE
Creation of service instance with name more than 50 characters fails

### ISSUE THREAD

**Issue by sg1702** [cloudfoundry/cloud_controller_ng#2111]
## Issue

Service instance creation fails when I tried to create the instance with name more than 50 characters. 

## Context

When I tried to create a service instance of name more than 50 characters, it failed with error: **You have requested an invalid service instance name. Names are limited to 50 characters.**
What is the reason behind this limitation? Is it possible to bypass this length restriction somehow as it breaks our live scenario? Also, I observed that the service key name has no length restriction, then why only service name?

**Comment by weymanf** [comment]
There is no work around for this because it is hard coded: https://github.com/cloudfoundry/cloud_controller_ng/blob/8887877b9dfc9237a34ffcbf54ac3cf58d680d48/app/models/services/service_instance.rb#L118

The reason behind it is unknown since this commit was made long ago, 2013. The database seems to hold the row to 255 chars. If there are strong arguments against this, we can bump up the length.

**Comment by blgm** [comment]
As @weymanf says the limit was added in 2013:
- story: (which may not be public): https://www.pivotaltracker.com/n/projects/254145/stories/50667131
  - makes it clear that there should be a limit of 50 characters for **user-provided** service instances
- commits:
  - https://github.com/cloudfoundry/cloud_controller_ng/commit/037a6d031c9d4227e1031a81c718ac4debc6ae55
  - https://github.com/cloudfoundry/cloud_controller_ng/commit/071297d5ada09f5e619ad3f99c5378c86f397766

Also it seems that the database limit of 255 is accidental due to a mistaken migration and an a revert that doesn't match:
- https://github.com/cloudfoundry/cloud_controller_ng/commit/94d17a3cde61ed5033d302f9b80aff398f80fffe
- https://github.com/cloudfoundry/cloud_controller_ng/commit/6c64161ba91df6e809d1e509f503e4b9aa85798b

It's clear that the limit of 50 characters is for a reason, but why?

I did find this bug (https://www.pivotaltracker.com/story/show/59171806) which mentioned an issue with AppDirect when a service name was longer than 50 characters. Perhaps the reason for a 50 character limit was because of a restriction in a particular service broker? My caution with increasing the limit is that we might just end up repeating history and discover the issue that caused folks to impose the limit in the past. Then again we might find that things have changed and it's all ok now.

**Comment by weymanf** [comment]
I agree with keeping this limit unless someone has a valid reason for going pass 50 characters.

**Comment by sg1702** [comment]
Since you mentioned that this restriction was added in 2013 and it's possible that the issue isn't relevant anymore, can you please relook into this length restriction? 
Our application creates service instances for dynamic string and this string can sometime be very huge (we don't have control over that). Hence, service creation of such instances fail. It is breaking in our production environment and it would really help if this limit could be increased.

**Comment by sg1702** [comment]
Business case: SAP Business Technical Platform is the platform for the Intelligent Enterprise where customers can achieve agility, business value, and continual innovation through integration, data to value, and extensibility of all SAP and third-party applications and data assets.

When customer signs a contract with SAP a new Global Account is created and as a self-service activity customers can create sub-account where they can get different product offering like SAP Cloud Platform Integration etc. While creating the sub-account they are required to provide an id which is the subdomain. Now if the customer wants to use some of the services then it is fine if the subdomain id length is up to 63 chars. However for the SaaS Integration service length more than 29 chars is a problem since we append certain pre-fixes for different bindings with the platform. Due to this the actual length which they can create is only 29 chars. Now we are facing escalations from some critical customers who already have subdomain ids longer than 29 chars which earlier they were using for other SaaS offering on the platform and they are not willing to change the sub-account as all SaaS products have to be then moved to new sub-account.

Technical problem: We use the subdomain name as the unique identifier for creation of service instances. The length of the sub domain can go up to 63 characters. With prefix of max 21 characters, our requirement is to be able to create service instances of max 63+21 =84 characters

**Comment by sg1702** [comment]
Business case: SAP Business Technical Platform is the platform for the Intelligent Enterprise where customers can achieve agility, business value, and continual innovation through integration, data to value, and extensibility of all SAP and third-party applications and data assets.
When customer signs a contract with SAP, a new Global Account is created and as a self-service activity customers can create sub-account where they can get different SaaS offerings like SAP Cloud Integration etc. While creating the sub-account they are required to provide an id which is the subdomain. Now, different SaaS service offerings are creating a platform resource (which in turn uses the cloud controller) with different length using the subdomain id.
Now we are facing escalations from some critical customers who already have subdomain id defined and are using some SaaS offerings. If they have to add certain other SaaS services then they are getting length restrictions from the platform. As a mitigation step we asked customers to change to new sub-account with a shorter length so that all the SaaS offerings are within the required length but they are not agreeing to move all SaaS offerings to new sub-account.
 
In order to address this we would like to have a uniform length and would like the Cloud controller team to extend this in general to 120 chars
 
Technical problem: Our SaaS offering uses the subdomain name as the unique identifier for creation of platform resources(like- service instances). The length of the sub domain can go up to quite a huge number (>50). So, our requirement is to be able create service instances with atleast max length of 120 characters.
