### ISSUE TITLE
Allow space application supporter to access specific audit event endpoints.

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2216]
## Issue

Allow space application supporter to access specific **audit event** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/audit_events/:guid
GET /v3/audit_events 

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these audit endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by ctlong** [comment]
Ran into trouble changing permissions on Event due to the controller's use of the old school `user_visibility_filter` function in the model.
https://github.com/cloudfoundry/cloud_controller_ng/blob/65a5edc1f644d8bf646635b2be2a958e411b9476/app/models/runtime/event.rb#L65-L75

Ideally, we want to update the controller to use Roles.
