### ISSUE TITLE
API endpoint `manifest_diff` is incorrectly marking processes as being removed and re-added rather than indicating process-level changes

### ISSUE THREAD

**Issue by elenasharma** [cloudfoundry/cloud_controller_ng#2248]
**Context**

Currently seeing remove and add operations rather than a replace operation when enough changes have been made to a process. This seems to be a result of the diffing library that is being used.

**Current Behavior**

```
{
  "diff": [
    {
      "op": "remove",
      "path": "/applications/0/processes/0/disk_quota",
      "was": "1024M"
    },
    {
      "op": "remove",
      "path": "/applications/0/processes/1",
      "was": {
        "disk_quota": "1024M",
        "health-check-type": "process",
        "instances": 1,
        "memory": "1024M",
        "type": "worker"
      }
    },
    {
      "op": "add",
      "path": "/applications/0/processes/1",
      "value": {
        "instances": 1,
        "type": "worker"
      }
    }
  ]
}
```

---

**Acceptance Criteria**

### Process changes should be shown via a `replace` operation

**Given** an app named `my-app` with one or more processes
**When** I make changes to one or more processes
**And** I use the `manifest_diff` endpoint
**Then** I should see in the diff a `replace` operation for the altered process(es)
**And** I should *not* see `remove` and `add` operation(s) for the altered process(es)

**Notes**

Consider whether sidecars are being implemented in the same way, may need to add a `sidecar` key.

**Comment by tjvman** [comment]
The `json-diff` gem uses a [`similarity` function](https://github.com/espadrine/json-diff/blob/6cac5769fba24db78cb1159e8139dd2148d45e2a/lib/json-diff/diff.rb#L192-L241) to determine if a given array element is present on both sides of a diff. If the calculated similarity is below a hard-coded threshold, the gem will treat the old element as removed and the new element as added (instead of a replace). For the `processes` array (or any array of JSON objects), removing enough key-value pairs from the object will push the similarity between the before and after versions of the object below the threshold, causing the behavior described in this issue.

The gem allows the caller to provide a custom similarity function. We plan to pass a custom similarity function that will compare the processes' `type` field. Since the `type` is unique per-process, comparing it should allow us to handle this case.

We may need to make a similar change for other arrays of objects in the manifest, like `sidecars` and `services`.
