### ISSUE TITLE
CCNG has no health endpoint that validates the health of the database connection

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/cloud_controller_ng#2264]
## Issue

CCNG provides a `/healthz` endpoint to allow health checks of the service, but this endpoint doesn't interact with the database, and therefore won't catch issues with the database connection. 

## Context

[An issue on cf-for-k8s](https://github.com/cloudfoundry/cf-for-k8s/issues/620) recently requested that we monitor the health of the database connection and restart the process/container when it becomes unhealthy, but there isn't currently an endpoint that makes that feasible.

For our purposes, we need the endpoint to require no validation and to respond with a 200 when the connection is healthy and with a 500-level code when it isn't.

## Possible Fix

One option would be to add a `/databasez` endpoint that is identical to `/healthz`, but performs some low-cost database interaction to determine success or failure. Another option would be to add optional parameters to the `/healthz` endpoint that can enable this additional check when desired.

Please let us know what you think. Also, /cc @braunsonm for any additional context he might want to add.

@matt-royal, @davewalter, @Birdrock, @acosta11, @heycait, @tcdowney

**Comment by Birdrock** [comment]
Each approach has merits, but I'd tend toward the consolidated `/healthz` endpoint. The `/healthz` pattern is fairly consistent across the industry (e.g.: Google), while a bespoke endpoint would not be. Since we are really worried about CC as a whole, rather than specific details, it makes sense to aggregate all health check permutations into a single endpoint. Independently, there could be health checks directly to the database, bypassing CC, but that may not be necessary.

Is the desire to make it an optional parameter in order to ensure backward compatibility?

**Comment by matt-royal** [comment]
@tcdowney filled me in on the background with the `/healthz` endpoint, and apparently it was an intentional choice to not exercise the database. At the time they thought that bringing CC down when the database is unstable was a bad behavior for the bosh-deployed version. I'm not sure if that's still true, but the optional parameter allows the k8s-deployed variant to test db health while the bosh-deployed one doesn't. I'd be fine including db-integration by default if that isn't an issue for anyone.

**Comment by braunsonm** [comment]
Thanks for creating this issue!

The only context I wanted to add on top of what Matt pointed out is that in a Kubernetes context I would rather unhealthly pods of CC be killed rather than continue running and returning only 500 errors. This way restarting the DB connection logic has a chance to resolve issues. For instance say you have a DB with a connection limit and 3 replicas of CC. Say one of those replicas hits the connection limit and starts returning 500's. I would like this pod killed/marked as unhealthy so traffic stops being load balanced to it.

**Comment by sethboyles** [comment]
I see in the [original issue](https://www.pivotaltracker.com/n/projects/966314/stories/166038540) there was already the consideration of something like `/healthz/advanced` which would check for connectivity with dependencies.  That could mean more than just the database though, (blobstore?) which may be more than what you all are looking for.

**Comment by sethboyles** [comment]
Since cf-4-k8s is no longer in active development, I am closing this unless we have other compelling use cases
