### ISSUE TITLE
Space Application Supporter can access specific app environment variable endpoints

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2271]
## Issue

Allow space application supporter to access specific app environment variable endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

- [ ] GET /v3/apps/:guid/environment_variables
- [ ] PATCH /v3/apps/:guid/environment_variables

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by stephanme** [comment]
There is an additional endpoint for application environment vars:
GET /v3/apps/:guid/env  = https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#get-environment-for-an-app
AFAIK, this one is used by "cf env".

GET /v3/apps/:guid/env
GET /v3/apps/:guid/environment_variables
are both controlled by the feature flags env_var_visibility and space_developer_env_var_visibility. Both api calls fail for space developers unless both feature flags are enabled.

Interestingly, PATCH /v3/apps/:guid/environment_variables is enabled for a space developer even if space_developer_env_var_visibility is disabled. I.e. env vars are write-only with disabled space_developer_env_var_visibility.


In our (SAP) foundations we have space_developer_env_var_visibility enabled so that space developers can see env vars including VCAP_SERVICES. However, Space Application Supporters shall not have access to VCAP_SERVICES (service credentials). Access (read/write) to application environment variables should be enabled so that supporters are able to configure applications.

I see two implementation options. Both involve a new feature flag space_application_supporter_env_var_visibility.

### Option 1

New feature flag space_application_supporter_env_var_visibility that controls visibility of env vars for Space Application Supporters the same way as space_developer_env_var_visibility does for Space Developers.

space_application_supporter_env_var_visibility | enabled | disabled |
---|---|---
GET /v3/apps/:guid/env | allowed, includes VCAP_SERVICES | forbidden
GET /v3/apps/:guid/environment_variables | allowed | forbidden
PATCH /v3/apps/:guid/environment_variables | allowed | allowed

:+1: consistent with existing functionality for space developers
:+1: no incompatible changes to existing CF API v3
:-1: Space Application Supporters can't read (but write) regular application env vars. Our use case is not fully covered.
:-1: inconsistency between read and write of env vars when feature flag is disabled (as in todays v3 api)
:-1: feature flag allows a configuration that is against the definition of Space Application Supporter role (shall not see technical credentials)

### Option 2

New feature flag space_application_supporter_env_var_visibility that controls visibility of env vars for Space Application Supporters but VCAP_SERVICES (maybe all system provided env vars) is redacted.

space_application_supporter_env_var_visibility | enabled | disabled |
---|---|---
GET /v3/apps/:guid/env | allowed, redacted VCAP_SERVICES | forbidden
GET /v3/apps/:guid/environment_variables | allowed | forbidden
PATCH /v3/apps/:guid/environment_variables | allowed | allowed

:+1: consistent with existing functionality for space developers
:+1: no incompatible changes to existing CF API v3
:+1: With enabled feature flag Space Application Supporters can read and write regular application env vars. Our use case is fully covered.
:-1: inconsistency between read and write of env vars when feature flag is disabled (as in todays v3 api)
:+1::-1: hardcoded handling of VCAP_SERVICES (but according to the definition of Space Application Supporter role)

**Comment by monamohebbi** [comment]
Hi Stephan,

We had an asynchronous discussion about this exact issue and responded to your thoughts into the [spreadsheet](https://docs.google.com/spreadsheets/d/1w07-1nlEXYzeDseT_BEKaT2T-QC-wZhNXrX4JPRrAYM/edit#gid=550044829&range=E34).

To summarize our thoughts: We are not thrilled about using the existing flag to allow space application supporters access to this endpoint since it is named after the space developer role. Renaming the flag is not an option and creating a new flag that would serve the exact same person seems like a hassle and would add would add unnecessary bulk to the API because the information that would have been presented in the redacted view can be collected by calling a combination of other existing endpoints that are not protected by a feature flag. For this reason we will just keep this endpoint as off limits and update the CLI implementation to not depend on this endpoint.

**Comment by stephanme** [comment]
Hi @monamohebbi,

thanks for the explanation. From your comment and the spreadsheet I understand the following access/visibility rules:

role<br/>space_developer_env_var_visibility | SpaceDeveloper<br/>enabled | SpaceDeveloper<br/>disabled | SpaceApplicationSupporter<br/>enabled | SpaceApplicationSupporter<br/>disabled |
---|---|---|---|---
GET /v3/apps/:guid/env | allowed | forbidden | forbidden | forbidden
GET /v3/apps/:guid/environment_variables | allowed | forbidden | allowed | forbidden
PATCH /v3/apps/:guid/environment_variables | allowed | allowed | allowed | allowed
GET /v3/environment_variable_groups/:name | allowed | allowed | allowed | allowed
"cf env" shows | app env, groups, VCAP_SERVICES | forbidden | app env, groups | forbidden |

Is this understanding correct?
The changes in "cf env" may get a bit ugly but otherwise this would cover our uses cases.

**Comment by monamohebbi** [comment]
Yes, this is a mostly accurate summary except we are not planning on adding the flag SpaceApplicationSupporter. So the table would look a little more like:

---|---|---|---|---
GET /v3/apps/:guid/env | allowed | forbidden | forbidden
GET /v3/apps/:guid/environment_variables | allowed | forbidden | allowed
PATCH /v3/apps/:guid/environment_variables | allowed | allowed | allowed
GET /v3/environment_variable_groups/:name | allowed | allowed | allowed
"cf env" shows | app env, groups, VCAP_SERVICES | forbidden | app env, groups

Our hope is that the SpaceDeveloperEnabled flag was mainly introduced to hide secrets and sensitive data - which we do not intend to show to the Space Application Supporter regardless (the redacted view).

Although - seeing this chart I'm wondering if there is a world where the following might be acceptable behavior:

---|---|---|---|---
GET /v3/apps/:guid/env | allowed | app env, groups | app env, groups 
GET /v3/apps/:guid/environment_variables | allowed | forbidden | allowed 
PATCH /v3/apps/:guid/environment_variables | allowed | allowed | allowed
GET /v3/environment_variable_groups/:name | allowed | allowed | allowed 
"cf env" shows | app env, groups, VCAP_SERVICES | forbidden | app env, groups

But I think there might be a risk in showing information that an admin might historically have been expecting to be secret? 

cc @piyalibanerjee

**Comment by stephanme** [comment]
I guess this is just a misunderstanding of the table header (I did not manage to format the table with 2 nested headings).
First line in the header is the role that the user has and second line is the value of the existing feature flag "space_developer_env_var_visibility". I.e. no separate feature flag for SpaceApplicationSupporters but todays implementation of the /v3/apps/:guid/env|environment_variables  is already controlled by feature flag space_developer_env_var_visibility.

The columns for SpaceDeveloper in my table should reflect the existing implementation for the env var endpoints. The feature flag space_developer_env_var_visibility controls the complete endpoint not just the sensitive env vars like VCAP_SERVICES:
- https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/v3/apps_controller.rb#L250
- https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/v3/apps_controller.rb#L265.

It would be surprising if a SpaceApplicationSupporter can see more than a SpaceDeveloper, isn't it? That's why I think that the feature flag space_developer_env_var_visibility should also control access for SpaceApplicationSupporters.

In our foundations we have space_developer_env_var_visibility enabled so I can also live without checking space_developer_env_var_visibility for SpaceApplicationSupporters.

**Comment by monamohebbi** [comment]
I agree that it would be confusing for a space supporter to see more than a space developer in certain cases. And it is good feedback to hear that you do not think it would be confusing to overload the space_developer_env_var_visibility flag. @piyalibanerjee is this something you could gather more feedback on?

**Comment by piyalibanerjee** [comment]
I agree with @stephanme -- I think it's fine to overload the flag -- that way there's no additional flag for the admins to toggle. We can also make a note of it in documentation of the flag. The only downside I see is if an operator team has a specific reason why they don't want to show env vars at all to space app supporters, but they do want to provide space developers that access, they would not have that level of granular control since the same flag would control both. But I don't think this would be a common case. And the app environment_variables endpoint shouldn't be revealing sensitive information in the first place, so even if in the worst case scenario the space supporters are able to view them, it shouldn't be detrimental from a security standpoint.

**Comment by will-gant** [comment]
Starting this now.

**Comment by will-gant** [comment]
Before continuing on this, could I just confirm that this story is indeed ready to be worked on and that the two endpoints that the new role needs access to are the two currently in the description?

i.e. 

 GET /v3/apps/:guid/environment_variables
 PATCH /v3/apps/:guid/environment_variables

**Comment by stephanme** [comment]
The description is correct. A more detailed and explicit description would go like this:

## Expected result
With enabled feature flag 'space_developer_env_var_visibility' a space supporter should be able access the following endpoints:

- [ ] GET /v3/apps/:guid/environment_variables
- [ ] PATCH /v3/apps/:guid/environment_variables

With disabled feature flag 'space_developer_env_var_visibility' a space supporter should be able access the following endpoints:

- [ ] PATCH /v3/apps/:guid/environment_variables

Note that the related endpoint GET /v3/apps/:guid/env is never accessible for space supporters because it exposes sensitive information (VCAP_SERVICES).

cf cli needs adaptions so that space supporters can use "cf env" (assuming feature flag 'space_developer_env_var_visibility' enabled). This is out of scope for this story.

**Comment by monamohebbi** [comment]
If we are moving forward with overloading the `space_developer_env_var_visibility` flag, then I think it should be fine to move forward with allowing a redacted view of `v3/apps/:guid/env`. Our initial reasoning not to do so was because we did not want to create a new flag. Since this is already picked up though I will create a new issue in the backlog.

**Comment by will-gant** [comment]
PR #2388 is now pending approval
