### ISSUE TITLE
Service Broker HTTP requests are only logged at debug level

### ISSUE THREAD

**Issue by andy-paine** [cloudfoundry/cloud_controller_ng#2292]
## Issue
Interactions with service brokers are only logged at debug levels

## Context
When a service broker is responding incorrectly, it is useful to be able to tell where in the Cloud Controller the requests to it originated from. This would help platform operators understand why a service or binding is in a certain state and the overall error rates of various brokers.

As service brokers represent fairly complex external systems that the platform operators may not have access to, being able to report what the Cloud Controller was trying to do is helpful when diagnosing integration issues with brokers. Debug logging is unfortunately far too noisy to be enabled the whole time so we would prefer this to be logged at either a different level or be able to enable debug logging specifically for service brokers.

## Steps to Reproduce
Enable `info` logging in CC - see no logs about service broker interactions
Enable `debug` logging in CC - see logs about requests and responses with service brokers

## Possible Fix
Raising this issue mostly to discuss approaches. As I see it there are a few different options we might take:
1. Change existing service broker client `debug` logging to `info` (affects all users)
2. Add additional (less rich) `info` level logging to the service broker client (affects all users)
3. Add a config option to include `debug` level logs specifically for the service broker client
4. Add a config option to log additional (less rich) `info` level logging in service broker client

Happy to contribute but would be good to get a steer on best direction given there is existing logging behaviour for the service broker client

**Comment by JenGoldstrich** [comment]
Hey Andy!

@sethboyles and I looked into this and found the place where you would make this change [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/a3a1fc74d0f66e4532d217714a6fedea808247866/lib/services/service_brokers/v2/http_client.rb#L72-L75)  We tested this locally and were able to see those logs, once concern we have is the headers being logged (which they are currently in debug).  We are seeing X-Broker-Api-Orginating-Identity followed by a token logged, this might not be a problem but we are unsure.

Seth and I like option 2, because then you wouldn't need to log the whole request body (which seems very noisy), we like the idea of adding info lines to the service-broker http client to capture request/response from the Service Broker.

**Comment by andy-paine** [comment]
That's really useful thanks @JenGoldstrich! I've raised https://github.com/cloudfoundry/cloud_controller_ng/pull/2293 which adds method, URL and the vcap request id (via the Steno context) and the response status which should hopefully be enough debugging information.
