### ISSUE TITLE
Possible error in v3 droplet documentation

### ISSUE THREAD

**Issue by MerricdeLauney** [cloudfoundry/cloud_controller_ng#2342]
## Issue
The [docs](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#update-a-droplet) implies that the only fields that can be changed are labels and annotations. However the [code](https://github.com/cloudfoundry/cloud_controller_ng/blob/fb80fc343fc3f00ddad6429cc3919eae2a3ab38e/app/controllers/v3/droplets_controller.rb#L77-L81) seems to imply that the image can also be updated?

Should the docs state that the image field can also be updated?

**Comment by ctlong** [comment]
I've some secondhand context on this from asking around:
> In CF for K8s we use kpack for staging and it produces runnable container images that include the stack. Stack updates require rebuilding the app's image entirely so to get those to propagate through it looks like the lowest friction way to do so was to update the droplets themselves and rollout the apps.

👾 **The ability to update the `image` field was apparently added as a way for the system to implement automatic stack updates from kpack in cf-for-k8s**
Only privileged users (read: admin or users with a certain scope) should be able to do this.

⚠️ **It's possible that the change accidentally allowed admins to update droplets in cf-for-vms**
Haven't confirmed this, but it's definitely how the code appears to work in the droplets controller. Even if this is true, we haven't received any complaints about this so far... maybe it's not a big deal?

✍️ **Updated the docs to (somewhat) reflect this reality in a [recent PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/2428)**
This PR updates the docs to reflect the image as an optional parameter if you have a certain scope. We left out admins potential permissions to update the image, as we aren't sure if that's intentional – something to follow up on with the cf-for-k8s folks maybe.

**Comment by sethboyles** [comment]
I don't think that admins being able to change the image is a big deal, and probably not worth noting in the docs or changing, especially now that cf-for-k8s is no longer actively developed.  If anyone feels otherwise, feel free to open a PR updating the docs or removing admin's permission.
