### ISSUE TITLE
Implement a clear and user friendly error message informing users they cannot access V2 endpoints while assigned the space supporter role.

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2385]
## Issue

Implement a clear and user friendly error message informing users they cannot access V2 endpoints while assigned the space supporter role.

## Context

We are hoping to avoid untangling the permissions logic in V2 which means the Space Supporter role will not be recognized as a permitted user by any V2 endpoint. This could lead to unexpected or unexplained output if a user with this role were to be using a platform that uses mixed V2 and V3 endpoints. Instead we want to catch any V2 calls early and consistently fail in consistent and user friendly way.

## Expected result
A space supporter should fail when curling any endpoint that is prefixed with a `v2`. The output of this message should inform them why they have failed and tell them to inform their platform admin that their permissions need to be changed.

## Acceptance
??

## Documentation
When I browse to any of these endpoints on [valid role types](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#valid-role-types) page of v3 docs, I can see an indication that this role is not recognized by any V2 endpoint, and will fail if a user attempt to curl any v2 endpoint with this role assigned.

**Comment by mkocher** [comment]
Discussed with @monamohebbi , going to investigate if this seems reasonably possible. Timeboxing investigation to a day.

**Comment by monamohebbi** [comment]
@mkocher @ctlong other things to consider while exploring:

Would it be possible to throw errors based on if the space supporter role is the only role assigned?
Would it be possible to throw errors only to endpoints that run through permission checks already (so endpoints that are available to even unauthorized users could continue to behave as expected)?

**Comment by mkocher** [comment]
did the spike, can do this pretty easily if we're willing to block all v2 access if assigned the space supporter role in any space. Take a look at the linked commit to see the minimal changes required. 

doing this more granularly would be substantially more challenging and probably require modifying v2 controllers one by one.

**Comment by stephanme** [comment]
I don't think that this global blocking is a good idea and from my point of view, the CF API v2 would behave unexpected and inconsistent. 

If a user is SpaceDeveloper in spaceA, this user can list all apps using "cf6 t -s spaceA; cf6 a". Now she/he gets additionally SpaceSupporter role for a different spaceB (maybe assigned by an org manager). When the user runs now the same "cf6 t -s spaceA; cf6 a" commands, she/he gets suddenly a 403. This makes little sense to me even if with a 'clear and user friendly error message' (... more words don't make it better ...).
I used cf cli v6 here just an example of a CF API v2 client. I know that it is out of maintenance.

Moreover, it would block cf cli v7 for all service related operations because they still rely on CF API v2.

I think that the current authorization logic in v2 is good enough. The SpaceSupporter role simply doesn't exist in v2 so you get a 403 unless you have additional roles. This is easy to explain and easy to understand I would say. The returned error message could contain a link to the [authorization documentation](https://docs.cloudfoundry.org/concepts/roles.html).

See also discussion + examples on https://cloudfoundry.slack.com/archives/C07C04W4Q/p1625853238142300

**Comment by monamohebbi** [comment]
@stephanme 

With out this error message, a user of cloud controller client who is unaware of the clients implementation details could run into very inconsistent behavior if the client still relies on some v2 endpoints. Using v7 of the cf cli as an example, a user would have no insight as to why their interactions with service commands are failing, but with an error message they at least could know what the solution is (upgrading to the V8 cli or requesting that their admin remove the role). Our goal in this error message is to prevent this role being assigned to a user of client that still relies on any v2 endpoints because then inconsistent behavior is highly likely, especially if the space supporter role is the only one assigned.

**Comment by stephanme** [comment]
Looks like we all have problems with SpaceSupport role and v2 API. And v2 is still used for some time...
Consensus is to avoid handling of the SpaceSupporter role for every single v2 endpoint. v2 implementation should not be touched at all or only in a generic way (e.g. middleware).

I see 3 options from the discussion above:

**Option 1**

Locking out users from v2 with a user friendly error message that have any SpaceSupporter role assignment.

Leads to unexpected responses when a v2 user has SpaceDeveloper role in a space and suddenly gets a 403 because someone (e.g. an org manager) assigned the SpaceSupporter role, maybe even in a different space.

**Option 2**

Locking out users from v2 with a user friendly error message that have only SpaceSupporter role assignments.

Avoids the unexpected behavior from option 1 in spaces where the user has additional roles.
Leads to unexpected behavior in mixed v2/v3 usage (e.g. cf cli v7) in spaces where SpaceSupporter is the only role but the user has additional roles in other spaces (same as option 3).

Addresses the use case where SpaceDevelopers and SpaceSupporter roles are assigned to different users only. I guess this is a common use case.

**Option 3**

Do nothing special and return the standard 403 on v2 calls if the user has (only) SpaceSupporter role for a space. The corresponding v3 call would succeed.

This leads to unexpected behavior in mixed v2/v3 usage (e.g. cf cli v7). Users may not understand why CF API v2 calls fail.
Simplest implementation, easy to explain, but surprising if users don't remember the v2 limitation and/or that the CF API client uses v2 and v3.

**Discussion/Proposal**
I still vote for option 3 but option 2 sounds good to me as well. I have trouble with option 1.

A final solution could be a configuration parameter for the v2 handling of SpaceSupporters.
E.g. ``cc.space_supporter_v2_handling``: 
- ``disable_user_with_any_space_supporter_role`` = option 1
- ``disable_user_with_only_space_supporter_role`` = option 2
- ``ignore_space_supporter_role`` = option 3

**Comment by monamohebbi** [comment]
Thank you for this feedback! I think option 2 is a good middle ground. I think we could combine it with a warning that links to the same documentation whenever the space supporter role is assigned to a user that different clients can either ignore or send forward depending on their implementation. 

I am open to having a flag that defaults to true. But to avoid overloading the API with many flags, what are your thoughts on renaming the current flag `temporary_enable_space_supporter_role` to `temporary_enable_space_supporter_role_v3_only` for clarity?

**Comment by monamohebbi** [comment]
I've created a new story to implement this error message based on option 2. Closing out this exploration story now.
