### ISSUE TITLE
 Applications deployed with `strategy --rolling` do not produce crash logs.

### ISSUE THREAD

**Issue by dzaslavskiy** [cloudfoundry/cloud_controller_ng#2587]
## Issue

Applications deployed with `strategy --rolling` do not produce crash logs.

## Context

Normally, when an application crashes it produces a log with a message detailing the crash:
```
App instance exited with guid f94d3889-3229-4045-befd-af282865dc2a payload: {"instance"=>"1016193b-39d2-42dc-69c8-27d9", "index"=>0, "cell_id"=>"b701ee4f-885a-4c07-80c1-036e3d494e0a", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>1, "crash_timestamp"=>1638762864524964378, "version"=>"0d53cd6f-6270-49e9-8ba8-1acd5d9efb58"}
```
However, if the application is deployed with `strategy --rolling` and then redeployed. It will not produce these log messages.

There is another log message that is associated with crashes. This message is produced for both types of deployment strategies but it does not contain all of the information of the above message.
```
Process has crashed with type: "web"
```

## Steps to Reproduce

Deploy application with `strategy --rolling` and then redeploy it again. Cause app to crash. It will not produce above log message

## Expected result

The application produces above log message regardless of deployment strategy.

## Current result

The application does not produce the above log.

## Possible Fix

This may be related to fact that with  `strategy --rolling`  the process GUID changes in differant way then with normal deployments.

**Comment by tcdowney** [comment]
Interesting, good find.

> This may be related to fact that with strategy --rolling the process GUID changes in differant way then with normal deployments.

I think your hunch is correct here. To make the v2->v3 migration easier the `web` process starts out with a GUID that is identical to its parent app's GUID. This allows it to be used almost interchangeably. Rolling deployments create new `web` processes so that causes the GUIDs to drift.

I think this also means crash events are broken for multi-process apps. We are sending the process GUID all the way through from [tps-watcher](https://github.com/cloudfoundry/tps/blob/fde3272c264a3e6538e8b289b7a93af450ff77a8/watcher/watcher.go#L136) to Cloud Controller, but at the point the event is created it is considering it to be an ["app" and not a process](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/internal/app_crashed_controller.rb#L21). I wonder if we could fix things by changing this call to actually pass through the app instead of a process.
