### ISSUE TITLE
Bump rails and related packagaes to v7.X

### ISSUE THREAD

**Issue by johha** [cloudfoundry/cloud_controller_ng#3438]
All rails related packages currently use rails 6.1.x. We should eventually upgrade to the latest v7 rails version.
Rails v7 contains a few breaking changes and cannot not easily be adopted.
Dependabot tried and failed:
https://github.com/cloudfoundry/cloud_controller_ng/pull/3431
https://github.com/cloudfoundry/cloud_controller_ng/pull/3332

Should be done by end of 2023.

**Comment by Gerg** [comment]
It looks like the PRs were failing due to the migration from the classic Rails autoloader to [Zeitwerk](https://github.com/fxn/zeitwerk).

It looks like we can do that migration [via configuration in Rails 6](https://guides.rubyonrails.org/classic_to_zeitwerk_howto.html#how-to-activate-zeitwerk-mode), so we can hopefully solve that problem prior to the Rails 7 upgrade.

**Comment by philippthun** [comment]
Rail upgrade (7.1) has been merged.
