### ISSUE TITLE
Service dashboard url should not be fixed in the ccdb

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/cloud_controller_ng#380]
If I provision a service that has a dashboard, its dashboard url is persisted in the service_instances table. What this prevents is me making any changes to the way that service dashboard is accessed in the future. If the domain or url format ever needs to change, I would either need to update the db directly or have users delete and recreate their services (not possible for persistent data services).

This also holds true for services that have no dashboard to start with but I introduce one in subsequent releases, those existing services have not way to locate their dashboard.

The service broker api could have an endpoint that returns the dashboard url for a given service instance, allowing the broker to be in control of future changes in that dashboard.

**Comment by shalako** [comment]
Hello John,

Instead of a specific solution for dashboard_url, what if we approached this in a more generic way. 

Your broker could return a new dashboard_url in response to [update-service operation](http://docs.cloudfoundry.org/services/api.html#updating_service_instance).  
- CLI UX would be `cf update-service myinstance` (existing command) with no arguments
- This would cause CC to call `PUT /v2/service_instances/:guid` on the broker (existing endpoint) with an empty body, and broker could return an updated dashboard_url.

Alternatively, would could potentially introduce a new user flow that triggers a `GET /v2/service_instances/:guid` to the broker.

**Comment by johnmcteague** [comment]
They key point here is that I, as the CF operator, changed the URL of the dashboard. My users should not need to take specific action to generate a new URL. 

A GET on /v2/service_instances/:guid would help, as a client I would call that each time I need to get the dashboard (if a user bookmarks it, then so be it)

**Comment by shalako** [comment]
Hi John,
Sorry for the delayed response; I've been out of the office.

I'm skeptical that every call to CC on GET /v2/service_instances/:guid should result in an equivalent GET to the broker but this may be the best option. I commonly run `watch cf service mydb` while testing broker behaviors, and leave it running for weeks at a time. This results in several API calls every 2s; if we passed these calls through to the broker, it just means more traffic on the broker. Maybe this isn't a concern?

I'd like to avoid adding a nested resource to the CC API for `dashboard_url` which would require API clients to make an additional call to get all info which is presently available to users with one command. I'd also like to avoid requiring users to use a separate CLI command to get `dashboard_url`.

I'll note this request and consider the implications this has on the system.

**Comment by geofffranks** [comment]
Is there any ETA on a fix for this?

**Comment by dieucao** [comment]
There is not currently an ETA on a fix for this.

**Comment by aashah** [comment]
There has not been any activity on this issue in the past year. We are closing the issue.

Please feel free to re-open.

CAPI Community Pair - @aashah @rizwanreza
