### ISSUE TITLE
job status url for diego droplet uploader

### ISSUE THREAD

**Issue by cromega** [cloudfoundry/cloud_controller_ng#387]
Our diego deployment is configured to rely only on consul to be able to talk to the CF API. The [droplet uploader](https://github.com/cloudfoundry-incubator/file-server/blob/master/handlers/upload_droplet/upload_droplet.go#L108) that runs at the end of the staging process  blows up when it tries to poll the job status. The job status URL is returned by the CloudController [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/presenters/api/staging_job_presenter.rb#L6). There seems to be no way to configure the CloudController to return cloud-controller-ng.service.consul instead.

**Comment by ematpl** [comment]
Hi, @cromega,

My apologies, this issues seems to have gotten lost in the shuffle. I think I understand the issue you're having. What are your reasons for making the externally facing CC API domain inaccessible from the Diego deployment?

Thanks,
Eric, CF Runtime Diego PM

**Comment by cromega** [comment]
@ematpl: No worries, it's not an urgent case.
There is no hard reason, it would be mostly for consistency. Throughout our Diego manifest consul URLs are used to reference different CF components, which means that theoretically the Diego deployment could operate with consul-agent as the only DNS server on the VMs as they don't need to communicate with the outside world. The blob uploader in CF, however, insists on returning a URL with the external domain in it.

**Comment by ematpl** [comment]
Sure, I see your point about the domain consistency. The DEA also still polls this same job URL when it [uploads](https://github.com/cloudfoundry/dea_ng/blob/master/lib/dea/utils/upload.rb) the droplet payload, so changing the job to use the internal consul URL would require the DEAs to have the consul agent present to provide DNS resolution for its domain. As Diego replaces the DEAs, and as we explore solutions such as Consul for dynamic internal service discovery instead of the gorouter, we may decide to change this, but I don't think we'll do so at present. Thanks for making us aware of it, though!

Best,
Eric
