### ISSUE TITLE
Can I use 'client_credentials' grant bearer token for GET /v2/events

### ISSUE THREAD

**Issue by dglozic** [cloudfoundry/cloud_controller_ng#433]
When I create a bearer token using 'authorization_code' grant to act on behalf of a user, calling /v2/events with a desired filter returns results.

However, what I would like to do is create a cron job that fetches all events since the last time I checked with a certain filter, and fires messages to downstream clients. I want my app to act on behalf of the client, not the user.

I created a bearer token using 'client_credentials' grant for a client that has 'cloud_controller.read' credential, and when I call any variation of /v2/events, I don't get errors for the bearer token, but I get zero results.

What type of credential do my client needs to have in order to be able to call /v2/events on behalf of itself, not the user? Is it even possible?

**Comment by zrob** [comment]
So what is happening here is that when you query /v2/events, the list you get back is scoped to events that the logged in user can read.  So the client you created does not have a corresponding user in CC with any Org or Space Roles, so there are no events that will be displayed. 

If you really want a client instead of a user, then the only type of client that will be able to see events is one with `cloud_controller.admin`.  That client could then see all events in the system, but would effectively be an admin.

Does that answer your question?

Thanks,
@zrob & @jberkhahn

**Comment by dglozic** [comment]
Yes, it does, thanks. It makes sense - you have to be an admin to get events related to other peoples' apps, services etc.

**Comment by dglozic** [comment]
Feel free to close the issue.
