### ISSUE TITLE
Allow User Provided Services To Have Tags

### ISSUE THREAD

**Issue by joefitzgerald** [cloudfoundry/cloud_controller_ng#451]
It would be nice to allow all service instance types to be tagged; currently only brokered services can be tagged. In the the following request, tags are ignored:

```
cf curl /v2/user_provided_service_instances -i -v -X POST -d '{
  "name": "my-ups-with-tags",
  "tags": ["my-tag","my-other-tag"],
  "credentials": {
    "password": "[PRIVATE DATA HIDDEN]",
    "username": "admin"
  },
  "space_guid": "REDACTED",
  "syslog_drain_url": ""
}'
```

**Comment by skibum55** [comment]
+1

**Comment by autodidaddict** [comment]
I think this is more than just nice to have. There are a number of reasons why organizations need to interrogate bound user-provided services. For example, a buildpack that requires categorization or taxonomy information on a bound service in order to determine how best to perform dynamic configuration. In situations like this, having tags on a UPS would be immeasurably helpful, as the alternative is to put the non-credential metadata in the credentials field, which is far from ideal.

**Comment by dieucao** [comment]
@joefitzgerald Thanks for the request.  We likely won't be working on this soon due to other priorities on the team.  Please let me know if you're interested in making a PR.  
Also, a little further out, we'll be looking at replacing user provided services with something we're calling Echo Service Brokers, which will be a more fully fledged user provided service, that can act exactly like regular services brokers.  With that, we hope that these deltas in functionality will go away.

**Comment by dave-malone** [comment]
+1. Spring Cloud Cloud Foundry Connectors look at tags, labels, and then also inspects the scheme for certain attributes in the Credentials block.

**Comment by jmnote** [comment]
+1

**Comment by SocalNick** [comment]
Closing per Dieu's comment above. We would consider a PR from community members that need this feature. There is long-term desire to replace UPSIs with an echo service broker.

**Comment by dwseiber** [comment]
I came across an interesting reason this would be necessary in some situations. RDS instances in some Cloud providers are expensive, so one clever thing a team can do to "fake" a UPSI into binding to a Spring Boot App is to create a UPSI with the precise credentials. Spring Boot looks for a tag "postgresql" and binds to that by default. Yes, you can explicitly configure the datasource, which I'm seeing at this very moment is probably the best way to go. I just thought it would be nice, for me, right now, as thats what I'm dealing with.
