### ISSUE TITLE
Combine endpoints

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#481]
The endpoints to associate some kind of user with an Organization and to do the same thing via username instead of guid should be combined in to a single endpoint that can take different JSON parameters or Query string fields. e.g.

http://apidocs.cloudfoundry.org/226/organizations/associate_auditor_with_the_organization_by_username.html
http://apidocs.cloudfoundry.org/226/organizations/associate_auditor_with_the_organization.html

**Comment by cgfrost** [comment]
Also, please make the documentation for remove/disassociate of the various users in an organization.

I don't care if you use the word disassociate or remove but please be consistent. 

e.g.
http://apidocs.cloudfoundry.org/226/organizations/disassociate_auditor_with_the_organization_by_username.html
and
http://apidocs.cloudfoundry.org/226/organizations/remove_auditor_from_the_organization.html

**Comment by dieucao** [comment]
I'm not quite sure because of the way the v2 api works if we're able to support specifying one of username or guid as required.
@utako @zrob Do you know if it's possible to update the newer end points to take a username field or a guid field?
Or perhaps there's another way of combining.
I think the point about the wording on the end points is fair and we should rename disassociate to remove on all these end points.

**Comment by cgfrost** [comment]
Thanks, the renaming will help a lot. We don't really care if you go with query parameters or JSON body parameters but someway to combine the endpoints would be great. Obviously we can live with it if it's not possible.

**Comment by sax** [comment]
We've made the documentation change, which will be deployed once it makes it through our CI pipeline. This looks to be triggered by a new cf-release release candidate.

We've made some comments in our tracker about combining the endpoints, but will close this ticket for now.
