### ISSUE TITLE
List all Service Bindings for the Service Instance documents invalid query parameter

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#496]
The API documentation for [List all Service Bindings for the Service Instance](http://apidocs.cloudfoundry.org/227/service_instances/list_all_service_bindings_for_the_service_instance.html) describes a `service_instance_guid` filter.  This filter is invalid as the `service_instance_guid` is included in URI instead

**Comment by Gerg** [comment]
This is due to the way that CC works for the v2 api and how the docs are generated. The same controller serves both `/v2/service_bindings` and `/v2/service_instances/:instance_guid/service_bindings`. `service_instance_guid` is a useful filter for the first case, but is kind of silly in the second. It is functional in the second case (you can provide another service instance guid and get an empty list). Because our docs automatically include all possible filters, it is automatically included, even though it is not useful.

**Comment by nebhale** [comment]
Can the documentation be updated to describe the fact that using this filter with anything other than the original `service_instance_guid` will be guaranteed to return an empty result?

**Comment by dieucao** [comment]
This will be fixed in the next cf-release that includes the above commit from cc.
You can see what it'll look like here:
http://s3.amazonaws.com/cc-api-docs/104228398/service_instances/list_all_service_bindings_for_the_service_instance.html
