### ISSUE TITLE
List Applications documents invalid query parameter

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#503]
The API documentation for [List all Applications](http://apidocs.cloudfoundry.org/228/apps/list_all_apps.html) describes an `organization_guid` filter. This filter is invalid, as `GET https://api.local.micropcf.io/v2/apps/ecb81f46-9e29-45fc-9519-60be35b2a292/routes?q=organization_guid:ebf76526-270a-4ccc-99a6-0c6981fb81a7` results in `CF-BadQueryParameter(10005): The query parameter is invalid: organization_guid`.

**Comment by wendorf** [comment]
Hello @twoseat,

Based on your HTTP request, it looks like you meant [List all Routes for the App](http://apidocs.cloudfoundry.org/228/apps/list_all_routes_for_the_app.html), where there's definitely an extra organization_guid filter parameter!

Since this will always be listing routes for a specific app that will belong to a specific organization, filtering by `organization_guid` isn't an operation that is very meaningful, so we have removed it from the docs.

If this fully addresses your concerns, please feel free to close this issue.

Thanks,
@wendorf and @karafelix 
CF CAPI Team

**Comment by dieucao** [comment]
Updated api doc here:
http://apidocs.cloudfoundry.org/release-candidate/apps/list_all_routes_for_the_app.html

Available in the next cf-release.

**Comment by twoseat** [comment]
Sorry for the bad link, and you're absolutely correct. Thanks for the update.
