### ISSUE TITLE
GET /v2/config/running_security_groups is not a paginated request

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cloud_controller_ng#578]
## Issue
```
GET /v2/config/running_security_groups
```
returns a paginated response (with pages) but the request is not documented as paginated. It is therefore apparently impossible to request page 2.

## Context
CC API 2.53.0, version 234 (latest version).  REST interface.

## Steps to Reproduce
Simply issue a `GET /v2/config/running_security_groups` request.  The response looks like this:
```
HTTP/1.1 200 OK
{
  "total_results": 3,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "3ce91b0a-e0ca-4a36-9fc7-f7a7fbcbe84f",
        "url": "/v2/config/running_security_groups/3ce91b0a-e0ca-4a36-9fc7-f7a7fbcbe84f",
        ...
      },
      "entity": {
        "name": "public_networks",
        ...
      }
    },
    ...
  ]
}
```
which is a paginated response. To build a complete list of "running security groups" one would expect to issue a series of page requests, but the request has no payload and is not paginated.

## Expected result
The result is fine, as far as it goes.
 
## Current result
I currently lack the ability to request page 2.

## Possible Fix
Extend the request to have a paginated request payload:

Name | Description | Valid Values
---- | ----------- | ------------
q | Parameters used to filter the result set. | Valid filters: name
page | Page of results to fetch	
results-per-page | Number of results per page
order-direction | Order of the results | asc (default) or desc

or some such.

## Notes
* The same (apparent) problem exists for `GET /v2/config/staging_security_groups`.
* This problem could be avoided by getting all security groups (`GET /v2/security_groups`) and filtering out the defaults ones, _however_ the API description of the _List all Security Groups_ request doesn't have any of the staging default or running default security groups in its example response, which implies they aren't returned.  Please clarify this in your response.

**Comment by adowns01** [comment]
Hi @Zteve, 

As a default, pages have `results-per-page` set to 50. So you can't get page 2 of your request because there is no page 2. 

We have updated our docs, in the locations that you mentioned, to include the pagination query parameters you can use. Our CI will update them on the internet when our tests complete. So, I'll list them below, too. 

| param | example |
| --- | --- |
|page | /v2/config/running_security_groups?page=2|
|results-per-page | /v2/config/running_security_groups?results-per-page=5|
|order-direction | /v2/config/running_security_groups?order-direction=asc or /v2/config/running_security_groups?order-direction=desc|

Thanks, 
@adowns01 && @sax, CAPI Team Members

**Comment by Zteve** [comment]
Thank you Amelia,
My problem is not that I can't _get_ page 2 but I cannot _ask_ for it. In the test that I ran I specified results-per-page=1 (to force multiple pages) but this query parameter was ignored.

I'm hoping that, apart from updating the docs, you also update CF to use the page query parameters in the normal way.

**Comment by Zteve** [comment]
As  you were; CF recognizes the query parameters; typo in my test. Thank you for your efforts.

**Comment by adowns01** [comment]
It happens to the best of us 😄
