### ISSUE TITLE
CF allows you to map routes which are too large [moved from gorouter]

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry/cloud_controller_ng#581]
## Issue

Please refer to the original issue by @Rylon in gorouter [cloudfoundry/gorouter#114]
## Steps to Reproduce

```
cf create-route <space> <domain> -n `printf 'a%.0s' {1..64}`
```
## Expected result

Cloud Controller should return an error when creating a route with host or domain name that is longer than specified in [RFC 1035](http://www.ietf.org/rfc/rfc1035.txt).
## Current result

```
Creating route aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bosh-lite.com for org o / space s as admin...
OK
```

```
curl aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bosh-lite.com
curl: (6) Could not resolve host: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bosh-lite.com
```

Thanks,
@ishustava, CF Routing Team

**Comment by wendorf** [comment]
Hi @ishustava,

Thanks for the issue! We just made a [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/cc1e640513bf2108e5f5e9dcb4105c384774f0e9) that should address this. We limit all labels (e.g. the parts separated by dots) to 63 characters, and limit the full visible domain name to 253 characters (although the RFC mentions the limit is 255 characters, the extra two characters come from the "invisible" byte denoting the length of the first label, as well as the termination byte).

If this looks good and you have no further questions, please feel free to close the issue.


Cheers,
@wendorf

**Comment by ishustava** [comment]
Thanks @wendorf, looks good!

**Comment by shalako** [comment]
@SocalNick because this started as a gorouter story https://github.com/cloudfoundry/gorouter/issues/114, the Routing team delivered the story to me just to verify we successfully handed it off. I missed that it was a no-op for us and tested the fix. I found that the error messages could be improved, primarily for creating a domain, and rejected our story with the following comments.

Do you want to have CAPI add this polish, or shall we?
Thanks

```
$ cf curl /v2/shared_domains -X POST -d '{"name":"a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1m.com"}'{
   "code": 130001,
   "description": "The domain is invalid: name format",
   "error_code": "CF-DomainInvalid"
}
```
**change error message to:** The domain is invalid: each label of domain name must be no more than 63 characters

```
$ cf curl /v2/shared_domains -X POST -d '{"name":"a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1"}'
{
   "code": 130001,
   "description": "The domain is invalid: name length_range",
   "error_code": "CF-DomainInvalid"
}
```
**change error message to:** The domain is invalid: name must be no more than 253 characters

```
$ cf create-route test a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.com --hostname a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.com
Creating route a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.com.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.com for org scoen / space test as admin...
FAILED
Server error, status code: 400, error code: 210001, message: The route is invalid: host format, host must be no more than 63 characters
```
**change error message to:** The route is invalid: host must be no more than 63 characters
("host format, " is superfluous)

```
$ cf create-route test a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1 --hostname a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1
Creating route a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1.a7UY012eT9xR4sCrnArk8StP3yRDq158U6UC9CXUXBZQ45jV7bm4og0RIS5QUY1 for org scoen / space test as admin...
FAILED
Server error, status code: 400, error code: 210001, message: The route is invalid: host must be no more than 253 characters when combined with domain name
```
**change message to** The route is invalid: route must be no more than 253 characters when host and domain are combined
(the key here is that the limit is not on the host but on route)

**Comment by SocalNick** [comment]
Thanks for the feedback, I'll write a story for CAPI to fix.

**Comment by michaelxupiv** [comment]
Hey @shalako,

Thanks for bringing up this issue. It seems like this has been fixed in this [story](https://www.pivotaltracker.com/story/show/118674741). We are closing this issue for now, feel free to reopen if you feel like we have not addressed your issue.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
