### ISSUE TITLE
List All Domains for the Space (deprecated) does not honour filter parameter

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cloud_controller_ng#584]
## Issue

The `GET /v2/spaces/<sp-guid>/domains?q=owning_organization_guid IN <org-guid>` request doesn't return a domain owned by the `<org-guid>` unless the space belongs to the same organization.

## Context

I'm testing the client API in `cf-java-client` and the `GET /v2/space/:guid/domains` request is documented to have a filter parameter called `owning_organization_guid`. I create two organizations and create a domain owned by one, and a space in the other, and specify the domain on the space create call.

A subsequent _List All Domains for the Space (deprecated)_ call filtering on the organization that owns the domain fails to return anything.

It also fails to return anything if I (erroneously) use the space organization as the filter value. However, if the domain is owned by the same organization the space is in, the list returns the correct result.

## Steps to Reproduce

1. Create two (disinct) organizations _orgId1_ and _orgId2_.
2. Create a domain *owned by* _orgId1_ (using _Create a Domain owned by the given Organization (deprecated)_ `POST /v2/domains`) and get the _domainId_.
3. Create a space *with parent* _orgId2_ (using _Creating a Space_ `POST /v2/spaces`) with a body that assigns the domain to the space: `{ "name": "aname",  "organization_guid": "<orgId2>", "domain_guids" : [  "<domainId>" ] }` and get the _spaceId_.
4. List the domains of the space, filtering on the owning organization guid: `GET /v2/spaces/<spaceId>/domains?q=owning_organization_guid IN <orgId1>&page=1`.

## Expected result

I expect a paginated response with a (single) domain resource in it, with id _domainId_.

## Current result

An empty page response.

## Possible Fix

Internal logic of the (underlying) query may be using an incorrect organization guid at some point.

**Comment by zrob** [comment]
@Zteve 

Given that this endpoint is deprecated, we would prefer not to make any updates to it.  Can you help us understand the use case you are trying to solve and maybe we can come up with a way to get what you need without using deprecated endpoints.

thanks,
@zrob & @rizwanreza

**Comment by Zteve** [comment]
Hi,
I'm trying to write the `domains.listSpaces()` part of the API for `cf-java-client`. I understand this API call is deprecated, but it should work properly, never-the-less. I have no alternative to getting it to work properly, since my goal is to provide complete coverage of the API; even if it is deprecated.

I would accept a solution that officially deletes the API call from the interface.

Thanks

**Comment by nebhale** [comment]
@zrob I'd agree with @Zteve that "deprecated" should mean that it will continue to work as documented until removed.  You can imagine a user that started to use this API before it was deprecated and is continuing to do so during the deprecation period.  Introduction of a bug during that time, should be considered a regression as the user has the expectation that their code will continue to work as it did previously.  

The Java Client is implementing deprecated endpoints because the CLI currently uses them and in order to ensure parity between CLI functionality and client functionality, we need to use the same endpoints.  While we could pick and choose which deprecated APIs we choose to implement (based on what the CLI uses), we've chosen to be consistent and either implement them all, or implement none of them.  We're aiming to ensure that a user can predict what documented APIs they can expect to be in the Java Client.

**Comment by SocalNick** [comment]
@Zteve owning_organization_guid doesn't really make sense when already scoped to a space. I've created a story to remove this, as well as a couple other fixes to that documentation: https://www.pivotaltracker.com/story/show/121425043

**Comment by Zteve** [comment]
Hmm; it made perfect sense to me, because "Owning organization" of a domain is _not_ the same as the parent organization of the space that is _assigned_ the domain. I thought it could sensibly return the results I expected (see above).

Removing the option entirely (in the docs) will 'solve the problem' by removing a feature that didn't do the right thing.
