### ISSUE TITLE
Domains API documentation does not document router_group_* fields

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#585]
The API documentation of all Domains and Shared Domains APIs ([example](http://apidocs.cloudfoundry.org/236/domains_%28deprecated%29/list_all_domains_%28deprecated%29.html), but not limited to) are missing a description of the `router_group_*` fields.

**Comment by zrob** [comment]
@nebhale 

router_group fields are not supported on the deprecated /v2/domains endpoints nor for /v2/private_domains.

router_group fields are only supported on shared domains.

on the shared domains docs it does look like we are missing a description for the readonly field router_group_type which we will update.

thanks,
@zrob & @rizwanreza

**Comment by nebhale** [comment]
@zrob Is there a reason that they were added (in the examples) of the deprecated endpoints?

**Comment by shalako** [comment]
@nebhale Cloud Controller magic, I expect. We only want the change in the /v2/shared_domains endpoints, but it magically propagated to any endpoint that references a domain; more than you've listed.

As Zach mentioned, `router_group_type` is read-only in all cases (CC passes this through from a backend API). The only endpoint `router_group_guid` is writable is `POST /v2/shared_domains` and there is a description for it http://apidocs.cloudfoundry.org/release-candidate/shared_domains/create_a_shared_domain.html

It sounds like you're asking for descriptions of fields in responses. Sounds great, but this is a much larger undertaking, as most pages in the doc provide example responses only.

@crhino

**Comment by michaelxupiv** [comment]
Hey @nebhale ,

Zach and Shannon brought up some good points here. The `router_group` fields are only available in the new shared domains endpoint, where `router_group_type` is a read-only field. Since we typically only provide descriptions for fields that are valid as parameters, our API docs exposes `router_group_guid` as opposed to its `type`. I'm going to close this issue for now, feel free to reopen this if you still have concerns.

Thanks,
CAPI Community - @michaelxupiv
