### ISSUE TITLE
A problem in a space quota with total memory limit 0 

### ISSUE THREAD

**Issue by mnitta** [cloudfoundry/cloud_controller_ng#616]
## Issue

An unknown error occurs when an application is deleted in a space, where a space quota with total memory limit 0 defined.
## Steps to Reproduce
1. Create a space
2. Push an application
3. Create a space quota in the space, with total number of application instances (-a), and total  memory limit 0.
4. Delete the application
## Expected result

The application is deleted successfully.
## Current result

cf command exits abnormally, with an error message 'An unknown error occurred.'

**Comment by MNitta** [comment]
The same problem occurs when a space quota with 'instance memory limit' or 'app instance limit' 0 is defined in a space, and an application in the space is deleted.

**Comment by utako** [comment]
Hi @MNitta,

I was unable to reproduce this as both admin and a space developer of a space. My steps were as follows:

1. `cf create-space-quota myquota -m 0M -a 0`
1. `cf push app`
1. `cf set-space-quota myspace myquota`
1. `cf delete app`

Which version of cf-release do you have deployed? What kind of user did you run this as?

Thanks,
@utako, CF CAPI Team

**Comment by MNitta** [comment]
Hi Utako,

We are using cf v235 and cf-cli v6.17.1. The problem occurred when we run the above test as admin. I have attached a snippet of cloud_controller_worker.log when the issue occurred.

[cloud_controller_worker.log.txt](https://github.com/cloudfoundry/cloud_controller_ng/files/317733/cloud_controller_worker.log.txt)

According to the callstack, an error occurred at mark_routes_changed in cloud_controller_ng/app/models/runtime/app.rb. It calls save function, so, validation_policies function is called subsequently. If total amount of memory is set to 0 in a space quota, MaxMemoryPolicy.new would raise an exception. The problem is, space quota checking is executed even if an application is deleted. I wonder such checking is needed in deleting an application.

We can reproduce this problem in V212 as well.

**Comment by zrob** [comment]
Hi @MNitta 

We are able to reproduce the error by running `cf delete [APPNAME] -r`, which attempts to delete the route along with the app.  If you delete the app first without the `-r` flag it should succeed.  You can then use the `cf delete-route` command to remove the route.

We will look into making the error message more informative.

Also, could you help us understand the use-case for setting a quota to zero? 

Thanks,
@zrob & @utako

**Comment by michaelxupiv** [comment]
Hello @MNitta,

> Also, could you help us understand the use-case for setting a quota to zero?

This will help us determine the urgency of the issue. 

Thanks,
@michaelxupiv & @rizwanreza

**Comment by thausler786** [comment]
@mnitta,

We're going to close this issue due to inactivity, but we're putting a story in our team's icebox to track this bug.  You can find this story here: https://www.pivotaltracker.com/story/show/121206631

Best,
@thausler786 && @ericpromislow
