### ISSUE TITLE
Removal of db.log_level / cc.db_logging_level

### ISSUE THREAD

**Issue by dcarley** [cloudfoundry/cloud_controller_ng#617]
076e68fa9325e7af176e305e238c9008d46a023f and c155c3c3a439d706a573451b392253ab4635f228 hardcoded the `Sequel` logging level that was previously configured by `cc.db_logging_level`.

Should the following be removed now that they're not used?

- `log_level` docstring for `VCAP::CloudController::DB#connect`
  - https://github.com/cloudfoundry/cloud_controller_ng/blob/e7452b01ed6dadde8fd0550c364b0ef79116fa9f/lib/cloud_controller/db.rb#L11
- `db.log_level` config options in `bosh-templates/`
  - https://github.com/cloudfoundry/cloud_controller_ng/search?utf8=%E2%9C%93&q=db_logging_level
- `cc.db_logging_level` property in cloudfoundry/capi-release specs
  - https://github.com/cloudfoundry/capi-release/search?utf8=%E2%9C%93&q=db_logging_level
- `cc.db_logging_level` property in cloudfoundry/cf-release examples
  - https://github.com/cloudfoundry/cf-release/search?utf8=%E2%9C%93&q=db_logging_level

I'd offer a PR, but I'm not sure how to co-ordinate it across that many release repos.

**Comment by thausler786** [comment]
Hi @dcarley,

Thanks for bringing these chores to our attention.  We've decided to revert 076e68fa9325e7af176e305e238c9008d46a023f and c155c3c3a439d706a573451b392253ab4635f228 since we decided that they were unneccessary.  For anyone interested, the story of these commits can be found in issue #572.

Best,

@thausler786, CAPI team member

**Comment by dcarley** [comment]
Reverts were e2dde7131a89f18a81b97d7455fc2c4a0814a099 and 23bc280af26b5f995ee8d4d54519ce71e67191e9. Thanks!
