### ISSUE TITLE
unhelpful error message creating service broker with incorrect json structure

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cloud_controller_ng#664]
Creating a service broker whose /v2/catalog incorrectly returns a map instead of a list under "services":

``` json
{"services" : {}} 
```

gives,

$ cf create-service-broker my-service-broker my-user my-password https://example.com/broker

Creating service broker my-service-broker in org ORG / space SPACE as me@example.com...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

**Comment by SocalNick** [comment]
@erjoalgo should it say something like "Invalid Catalog"?

**Comment by ericpromislow** [comment]
The error message has improved in the interim time since the problem was reported. It's now like this:
```
$ cf create-service-broker sb1 admin admin http://sb.bosh-lite.com
Creating service broker sb1 as admin...
FAILED
Server error, status code: 502, error code: 270012, message: Service broker catalog is invalid:
Service broker must provide at least one service
```

However, if I construct a non-empty hash of services, I'll most likely end up with UnknownError messages related to unexpected types.

There is an [initiative](https://docs.google.com/document/d/1-IKI-PwPnhtbK0su1UzWA_UoyaCjL8S2d6ky3Xmuwvg/) to provide catalog schemas so that service broker providers can validate their own catalogs.
This makes more sense than having the cloud-controller duplicate the error-checking.

We're going to close this issue, but feel free to reopen if you have more comments.

@ericpromislow & @utako, CAPI team.
