### ISSUE TITLE
CF list Application Security Group inconsistency

### ISSUE THREAD

**Issue by Selvaguru** [cloudfoundry/cloud_controller_ng#669]
## Issue

As a space developer, I am not able to see all ASGs that are part of either default_staging or default_running set. But, response while retrieving single ASG or ASGs associated with a space, includes two properties default_staging and default_running.  
## Context

As a space developer, when I retrieve all ASGs bound to my space **(/v2/spaces/188c6f07-0add-460e-94d7-f0ecfb0a2171/security_groups)** or a particular security group **(/v2/security_groups/248ea13d-dd3b-4f9e-84ce-353b69fde797)**, I can identify whether the security group is part of running_default or staging_default.

However, when I try to see all ASGs of either running_default or staging_default (**/v2/config/staging_security_groups**), it throws the following error:

``` json
{
   "code": 10003,
   "description": "You are not authorized to perform the requested action",
   "error_code": "CF-NotAuthorized"
} 
```

Is it a bug? Or is there any rationale behind this behavior ?

**Comment by ronakbanka** [comment]
@Selvaguru  `/v2/config/staging_security_groups` endpoint can be queried only by users having admin role.
Related cc code: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/controllers/runtime/security_group_staging_defaults_controller.rb#L47

**Comment by Selvaguru** [comment]
@ronakbanka Yes!  that is exactly the question. While this API is restricted to admins, i can still see a group if it is a part of 'default_staging'. is this okay?

**Comment by ronakbanka** [comment]
`/v2/service_groups` is a user api so getting information about security group shouldn't be a issue , as those security groups give details about outbound access for staging phase and app running phase. 

Maybe someone from pivotal can answer in more detail.

**Comment by PadmaB** [comment]
We see an inconsistency in the behavior between CLI and v2 APIs and hence would like to understand the reasoning:
1. CLI command **cf staging-security-groups** expects the user to have admin role. This indicates that the data might be secure and hence needs specific permissions. Not really sure what data does it return, but assume that it returns the list of security groups assigned to default-staging group set
2. v2 API **/v2/security_groups** actually returns a list of security_groups which is similar to the command **cf security-groups**. However, it returns additional information on the security-group as well, if it is assigned to default-staging group set or default-running group set

This seems bit inconsistent, on one hand with cli command it looks like getting the group set assignment of security groups to default-staging and default-running group set is protected [need admin role] but on the other hand that information somehow can be retrieved via the v2 APIs.
Since the action is read-only but with different behavior, it leads to confusion.

**Comment by SocalNick** [comment]
I agree, this is confusing. The CLI is using [Security Group Staging Defaults API](cf staging-security-groups) to display staging security groups which is restricted to the `cloud_controller.admin` role.

@dieucao can you think of a reason why `GET /v2/config/staging_security_groups` and `GET /v2/config/running_security_groups` shouldn't be accessible to a regular user? Users can already list `/v2/security_groups` which indicate whether the group is `running_default` or `staging_default`.

**Comment by krishicks** [comment]
Given that ASGs are *whitelists*, and those in staging/running apply to all containers, I don't see why those endpoints shouldn't be accessible to a regular user. They have access to those endpoints; what's the point in hiding the list, or the content of those security groups?

**Comment by PadmaB** [comment]
From the above conversation should I consider that ideally there is no need for restricted access to view the running_default or staging_default security groups via CLI?
If yes, will the behavior for CLI be changed going forward?

**Comment by krishicks** [comment]
@PadmaB @dkoper is the CF CLI PM; maybe he'll chime in.

**Comment by ericpromislow** [comment]
Hi @Selvaguru,

We've addressed this in [this commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/db57cd21c4e5c52ccc4e2452503756f5d610a912), and have made these endpoints visible to non-admins. Hope this helps. Feel free to reopen this issue.

Thanks,
@ericp and @utako, CF CAPI Team
