### ISSUE TITLE
A regular user can see a space or an org even if the regular user doesn't have enough rights

### ISSUE THREAD

**Issue by NAGAI-Tsuyoshi** [cloudfoundry/cloud_controller_ng#702]
## Issue

A regular user can see a space or an org even if the regular user doesn't have enough rights
## Context

It is necessary to have authority of creating and see org/space via cli ie. cf create and cf orgs/spaces. This authority is given as a role by administrator. If a regular user is targeted org OrgA as “OrgAuditor”, the regular user cannot know a space name and even whether the space like SpaceA and SpaceB exists in OrgA or not. However, if the regular user uses create-space command, the regular user can know whether the space exists or not.

  We are running an on-premise CF installation, and using the following versions:
    ・CF version is 240
    ・Diego version is v0.1481.0
## Steps to Reproduce

[case1 when creating an org]
1.  Login as a regular user
2.  Use create-space command for org which the regular user is not a member 

[case2 when creating a space]
1.  Login as a regular user
2.  Target org only or org and space.
a)  Only target org 
org role : “Billing Manager” or “Org Auditor” or Nothing
space role : Nothing
b)  Target org role and space
org role : “Billing Manager” or “Org Auditor” or Nothing
space role : “Space Manager” or “Space Developer” or “Space Auditor”
3.  Use create-space command for a space which the regular user is not a member in the regular user’s org.
## Expected result

In the case of steps to Reproduce, create-space command fails to carry out and returns error message as below because the regular user does not have enough right. 
Server error, status code: 403, error code: 10003, message: You are not authorized to perform the requested action
## Current result

In fact, the error message does not return. Instead of it, the message returns “Space SPACE already exists”.  
This result means the regular user can know space exists in an org nevertheless the regular user is not assigned the space.
However, when user try to create space does not exist in an org, the result is the same as Expected result.

**Comment by SocalNick** [comment]
Hi @NAGAI-Tsuyoshi,

Thanks for reporting this issue. Unfortunately, this is a tough issue to fix because of how much the V2 API uses base classes for a lot of the model functionality. We could try to fix, but we are worried that it could cause more harm than good.

Instead of fixing this, could we share with you some of the work in progress:
* We are working to deliver replacement capability with the V3 API that is much easier for developers to work with. It might take some time, but we'll eventually get to Org and Space management.
* We will eventually support finer-grained permissions managed by UAA, which will require us to rethink how we authorize users to create resources.

We understand that the current behavior isn't ideal, but given that it's difficult to fix and it could be argued that an OrgAuditor should be able to at least know all the Spaces that exist in an Organization, we are going to close this issue.

cc @luan
