### ISSUE TITLE
allow empty app_domains again

### ISSUE THREAD

**Issue by ampersand8** [cloudfoundry/cloud_controller_ng#713]
**Issue**
Since the commit [ab24f0a3bab0f49abcb05a43968bb52d1d65592a](https://github.com/cloudfoundry/cloud_controller_ng/commit/ab24f0a3bab0f49abcb05a43968bb52d1d65592a) it's mandatory to set at least one app domain in cf.yml. So we're currently forced to set a fake domain, which is visible but not of any use to the customer.

**Context**
Deployment of cf with bosh with capi 1.7.0. when no app_domain is set in cf.yml.

**Solution suggestion**
I would suggest to revert commit [ab24f0a3bab0f49abcb05a43968bb52d1d65592a](https://github.com/cloudfoundry/cloud_controller_ng/commit/ab24f0a3bab0f49abcb05a43968bb52d1d65592a), so that people can choose whether or not they want to set an app_domain as PaaS provider.

**Comment by SocalNick** [comment]
Hi @ampersand8 - I think we can remove this constraint. We were trying to [improve the seeding code to allow a subdomain of the system domain](https://www.pivotaltracker.com/story/show/126431473), but I don't think the requirement of having app_domains is necessary.

CAPI, whoever picks this up, I think it's ok to revert that commit, please let me know otherwise.

**Comment by nicregez** [comment]
Thanks a lot @SocalNick for helping us with this issue.
By when are you going to release it, or more precisely, in which CF release will we see this fixed?

**Comment by SocalNick** [comment]
Best I can do is "upcoming release". The CAPI team has been struggling a bit with CI which has caused acceptance to pile up. Thanks for your patience in the matter.

**Comment by SocalNick** [comment]
Fixed in https://github.com/cloudfoundry/capi-release/releases/tag/1.12.0
