### ISSUE TITLE
Issue while updating user to space role

### ISSUE THREAD

**Issue by samantaditya** [cloudfoundry/cloud_controller_ng#772]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Hi Team,

Can you please suggest, how can we retrieve the PCF logs that are generated while using REST endpoints. 
we are facing an issue while associating space role to user, it works from REST endpoint for few order and fail for few orders for 400 error 
in the error log we just get "returned a response status of 400 Bad Request"

PUT url : domain/v2/spaces/spcGUID/developers 
Input payload : {"username": "abc@xyz.com"}

The CF trace mentions very generic error "400 Bad Request"

We also tried using inline endpoint

PUT url : domain/v2/spaces/spcGUID/developers/userGUID 

Thanks

**Comment by ljfranklin** [comment]
Hi @samantaditya, sorry you're having trouble with CC. The following might help narrow down the problem:

1. `cf -v curl /v2/spaces/SPACE_GUID/developers -X PUT -d '{"username": "SOME_USER"}'`
1. The response should include a `X-Vcap-Request-Id: LONG_REQ_GUID` in the header.
1. SSH onto one of the CC API VMs (e.g. `api_z1`)
1. `cat /var/vcap/sys/log/cloud_controller_ng/cloud_controller_ng.log | grep LONG_REQ_GUID`

See if anything immediately jumps out, otherwise feel free to send us a sanitized set of logs from the VM. If you do figure out the problem, please let us know as we may be able to improve the error message.

**Comment by samantaditya** [comment]
Found this error when checked from CF curl

HTTP/1.1 400 Bad Request
Content-Length: 132
Content-Type: application/json;charset=utf-8
Date: Wed, 08 Feb 2017 13:19:50 GMT
Server: nginx
X-Cf-Requestid: fd6583cb-4a1540eccead
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 5f7eaa0c-c811::ea5211c4-ef1b-885bf0fd5cb1

{
  "code": 1002,
  "description": "Invalid relation: c657d10e-fd4c-4c89-a09a-0619ac2fbdbe",
  "error_code": "CF-InvalidRelation"
}
Can someone suggest.

**Comment by rboykin** [comment]
@samantaditya In order for a space role to be set for a user, that user must first hold the role of "user" in the space's organization.  The cf CLI hides this from you.  But, if you turn on cf CLI trace prior to running cf set-space-role, you will see two PUTs are made, one to /v2/organizations/guid/users and one to /v2/spaces/guid/developers.  You have to do the same if you want to use cf curl directly.

**Comment by samantaditya** [comment]
Yes @rboykin, Thanks it worked for me, the issue was with the organization guid not getting mapped with the organization user role due to which when trying to associate the user guid to space role it used to fail for Invalid relation.
