### ISSUE TITLE
Checksum validation fails for faraday_middleware-0.11.0.gem

### ISSUE THREAD

**Issue by kdykeman** [cloudfoundry/cloud_controller_ng#787]
## Issue

When running `bundle install` the following disconcerting message comes up:
>Bundler cannot continue installing faraday_middleware (0.11.0).
The checksum for the downloaded `faraday_middleware-0.11.0.gem` does not match
the checksum given by the server. This means the contents of the downloaded gem
is different from what was uploaded to the server, and could be a potential
security issue.

## Context

See https://github.com/bundler/bundler/issues/5332

## Steps to Reproduce

Run `bundle install`

## Expected result

Bundler doesn't complain about the checksums not matching.

## Current result

Bundler complains about the checksums not matching (see screenshot)

## Possible Fix

Update to a newer version of faraday_middleware where the community asserts the checksums match.

## `name of issue` screenshot
![screen shot 2017-03-06 at 3 28 17 pm](https://cloud.githubusercontent.com/assets/3085509/23634915/b379cc8a-0281-11e7-8ef0-6c59a5d06004.png)

**Comment by michaelxupiv** [comment]
Hey @kdykeman ,

Thanks for submitting this issue. It does look like this is a known faraday_middleware / rubygems issue. However, we are only pulling in this gem because of `fog-azure-rm`, and it feels a bit weird to have this explicitly specified in our Gemfile. I would suggest submitting an issue / PR to `fog-azure-rm` to get this fix (and sometime in the future we can bump our fog-azure-rm version). For the short term, I would suggest to just downgrade your bundler to a version before they started validating checksums. Closing this issue for now, feel free to reopen if you have any concerns.

Thanks,
CAPI Community, @michaelxupiv

**Comment by zrob** [comment]
A link for more information: https://github.com/bundler/bundler/issues/5332

**Comment by Gerg** [comment]
Relevant issues:
* https://github.com/rubygems/rubygems.org/issues/1551
* https://github.com/bundler/bundler/issues/5332
* https://github.com/Azure/azure-ruby-asm-core/issues/32
* https://github.com/lostisland/faraday_middleware/issues/152

**Comment by zrob** [comment]
The linked issues seem to indicate that azure gem has been updated and we can bump it to get the updated version of faraday_middleware.  Reopening until we rule out bumping the dependency.

**Comment by kdykeman** [comment]
Thanks @zrob, I spotted that today as well when looking upstream.

**Comment by Gerg** [comment]
The chain is: 
`cloudfoundry/cloud_controller_ng` > `fog/fog-azure-rm` > `Azure/azure-storage-ruby` > `Azure/azure-ruby-asm-core` (checksum issue) > `lostisland/faraday_middleware` (checksum issue)

**Comment by zrob** [comment]
@kdykeman a fix should be available on master now.  Would mind verifying that you are able to bundle?

thanks!

**Comment by kdykeman** [comment]
@zrob Thanks!  I am now able to bundle.
