### ISSUE TITLE
`router.route_services_secret` is used as a boolean

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cloud_controller_ng#808]
cloud_controller_ng's spec has a `router.route_services_secret` that it only uses to determine whether or not route services are enabled. This property should be deprecated in favor of an actual boolean like `router.route_services_enabled`.

**Comment by nicregez** [comment]
Hi Wendorf

This is a valid suggestion, thank you! We will check with our product manager if they support your input and let you know. @zrob What are your thoughts?

Mike & Nic

**Comment by zrob** [comment]
@shalako @shashwathi do you have a thought on how cc should learn this?

maybe routing release exposes a link called supported_features and this is in the list?  or maybe it's just a boolean link?  are there other booleans that releases would want to know about?

**Comment by shashwathi** [comment]
@zrob  @wendorf 

> do you have a thought on how cc should learn this?

I am not sure its a good idea to introduce a new property to gorouter because the job of the property seems redundant. If the value is set to empty string / not set, gorouter understands that route service is not enabled. Does CC not care about the value of route service ?  Why does CC need to learn about route service enablement? 
If CC does not care about the value then it doesn't seem crazy to expose a link to inform CC whether route service is enabled or not.

> maybe routing release exposes a link called supported_features and this is in the list? 

This is good idea for future proofing but do we have any use cases for adding supported_features on gorouter?

@abbyachau thoughts? 

Regards
Shash

**Comment by charleshansen** [comment]
Looks like this is not important enough to update gorouter at this point. Closing the issue for inactivity.
