### ISSUE TITLE
Provide a Root CA when creating/updating service broker

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cloud_controller_ng#825]
When I register or update a service broker, I'd like to offer `https://` URLs to my broker but the SSL certs are often self-signed. I'd like to be able to have users register my broker with the matching root CA for the SSL/TLS certs please.

Currently, if the service broker has self-signed certs then I'm required to downgrade to accessing/registering the broker via `http://`

**Comment by zrob** [comment]
@drnic We're putting together a track of work to remove the `skip_cert_verify` option such that we are secure everywhere by default.  The service broker interaction is one of the stickier ones since we can't supply CAs in a bosh manifest.  This sounds like it could be our solution.

**Comment by mattmcneeney** [comment]
Hey @drnic 
We're just taking a look at this issue; is this still something that is important for you?
Thanks!

**Comment by drnic** [comment]
It’s only important to me if it’s important to you :)


________________________________

**Comment by zrob** [comment]
This still sounds valuable to me.  We've been working on turning http to https everywhere we can.  This can be done for brokers if the brokers are using a cert that the vm cc is running on trusts it, but doesn't allow operators to easily opt-in to self-signed certs without putting them into the cc vm trust store.

**Comment by mattmcneeney** [comment]
I think that platform to service broker communication still supports both
HTTP and HTTPS though. Are/were there plans to disable HTTP?

**Comment by mattmcneeney** [comment]
Closing for now, but will reopen if this becomes a blocker for anyone!

**Comment by tcdowney** [comment]
Reopening this since cf-for-k8s redirects `http` to `https` by default. This makes this and issue since users can't just downgrade to `http` when they're trying to interact with on-platform brokers.

See this Slack convo where @reneighbor ran into this today:
https://cloudfoundry.slack.com/archives/C017LDM6KTQ/p1602280933144500

cc @piyalibanerjee @Gerg

**Comment by jamespollard8** [comment]
Now that we (the cf-for-k8s team) understand this better, we're thinking that we made need a K8s implementation of this: https://bosh.io/docs/trusted-certs/, so that we could potentially use a self-signed CA by adding it to the trust store for [at least] the necessary containers.

Does that make sense to you, cake folks?

**Comment by sethboyles** [comment]
Closing this since cf-for-k8s is no longer under active development
