### ISSUE TITLE
Log streaming services can't provide multiple syslog_drain_url

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cloud_controller_ng#826]
## Issue

Log streaming services can't provide multiple syslog_drain_url

## Context

Currently a log streaming service can only provide a single URL in the binding response. 

> syslog_drain_url	string	A URL to which logs may be streamed. "requires":["syslog_drain"] must be declared in the Catalog endpoint or the platform should consider the response invalid.
https://docs.cloudfoundry.org/services/api.html#binding

In certain setups it would be desirable to allow multiple URLs to be provided for availability and load balancing purposes.

## Steps to Reproduce

Bind a log streaming service with multiple syslog_drain_url to an app

## Expected result

Either of:
- Logs are streamed to one of the the syslog_drain_url; if this becomes unavailable a new connection is opened to one of the other syslog_drain_url provided and logs resume streaming (for availability)
- Each currently available syslog_drain_url receives a "subset" of the logs in parallel (for availability and load balancing)

## Current result

Not supported. Only one syslog_drain_url can be provided. If this become unavailable logs are irretrievably lost.

**Comment by Gerg** [comment]
Hey @CAFxX,

Thank you for your feature request. 

Since this is part of the [open service broker specification](https://www.openservicebrokerapi.org/), you would have to submit this issue [on their github](https://github.com/openservicebrokerapi/servicebroker).

A couple idea that may or may not address your use-case:
- Users can bind multiple logging services to a single app for higher availability (at the cost of duplication)
- The logging service can do its own load balancing behind the single url

I'm going to close this issue for now, but please re-open it if you have questions or concerns.

- @gerg && @ericpromislow
