### ISSUE TITLE
Create-service-broker does not seem to actually create a service broker for openbroker

### ISSUE THREAD

**Issue by elanakoren** [cloudfoundry/cloud_controller_ng#827]
## Issue

When we run `cf create-service-broker openbroker <USERNAME> <PASSWORD> https://openservicebroker.cfapps.pez.pivotal.io --space-scoped`, we receive a 201 response. However, when our app hits the `/services` endpoint, it only *sometimes* returns the data for the service in question. (It usually doesn't, but occasionally does.)

## Steps to Reproduce

1) Run cf create-service-broker openbroker <USERNAME> <PASSWORD> https://openservicebroker.cfapps.pez.pivotal.io --space-scoped
2) Hit [YOUR-CF-URL]/organizations/[YOUR-ORG-GUID]/services?results-per-page=100&inline-relations-depth=1&page=1
3) Note that the service you added in step 1 does not show up in the results.

## Expected result

The service you just added *should* show up. 

Any help would be appreciated. Thanks!

**Comment by Gerg** [comment]
Hey @elanakoren,

Thanks for submitting this issue. We were able to reproduce the space-scoped broker not appearing in `GET /v2/organizations/:guid/services`. However, we are not sure how to explain it appearing sometimes.

I'll talk with our PM @zach about whether it is expected for space-scoped services should be present in the org services list, since they are only available for the space they are scoped to, not the entire org. That said, space-scoped services do appear in the top-level `GET /v2/services` endpoint, so there may be an argument for them appearing here.

Thanks.
@gerg && @ericpromislow

**Comment by elanakoren** [comment]
Hi @Gerg @ericpromislow,

Thanks for getting back to me. I see that I missed a subtlety in my original issue, but I suspect there's still a bug here. We found that we could run cf create-service-broker [broker-name] [broker-url] --space-scoped, then hit  [YOUR-CF-URL]/spaces/[YOUR-SPACE-GUID]/services?results-per-page=100&inline-relations-depth=1&page=1, and we still wouldn't see the service we added. 

For what it's worth, the service does show up when we hit the general /services endpoint, but it should show up under both.

Thanks,
Elana and @elenasharma

**Comment by zrob** [comment]
I spoke with @elenasharma in person about this.

We can ignore the `/v2/organizations/:guid/services` endpoint as they are actually using `/v2/spaces/:guid/services`.  The real issue we need to focus on is that they are seeing that services they expect to be visible are not always in the list.

CAPI has not been able to reproduce this, so we're hoping that if it is observed again then somebody can come over and grab our interrupt pair to investigate the environment directly.

**Comment by aashah** [comment]
Hey @elanakoren,

Your team experienced this issue again today and asked us to take a look at the environment. We believe we've found the root cause. `/v2/spaces/:guid/services` does not seem to respect the `cloud_controller.admin` scope.

We were able to confirm this by creating a SpaceDeveloper and running `cf curl /v2/spaces/$(cf space <my-space> --guid)/services | jq -r .resources[].entity.label` to see the service. When doing the same as the admin, it was not present.

/cc @zrob 

CAPI Community Pair
Aakash & @ericpromislow 

---
Technical:

The [endpoint](https://github.com/cloudfoundry/cloud_controller_ng/blob/8a8f7a3fbbc84daae6d96caecf368a09e7c9fb81/app/controllers/runtime/spaces_controller.rb#L103) in the SpaceController uses [`Service.space_or_org_visible_for_user(space, SecurityContext.current_user)`](https://github.com/cloudfoundry/cloud_controller_ng/blob/8a8f7a3fbbc84daae6d96caecf368a09e7c9fb81/app/models/services/service.rb#L60). This method tests for [Space membership](https://github.com/cloudfoundry/cloud_controller_ng/blob/8a8f7a3fbbc84daae6d96caecf368a09e7c9fb81/app/models/services/service.rb#L60) to know whether to include space-scoped service brokers. This test [does not include](https://github.com/cloudfoundry/cloud_controller_ng/blob/8a8f7a3fbbc84daae6d96caecf368a09e7c9fb81/app/models/runtime/space.rb#L146-L149) checking for the admin scopes.
