### ISSUE TITLE
[feature request] Restrict access to organization by network

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cloud_controller_ng#838]
For compliance reasons, we're looking into ways to restrict api access to a given org and its spaces / apps / services / etc by ip address--for example, the owner of an org might want to ensure that all access to that org comes from the owner's employer's network. Would you all be interested in adding this feature to the cloud controller or reviewing a patch to add this functionality?

cc @cnelson @mogul

**Comment by zrob** [comment]
@jmcarp @cnelson @mogul, sorry for the slow response.

This is an interesting feature idea. I'm concerned about the potential complexity something like this could introduce. I'd be curious to know what a patch for this might look.  

Specifically I'm interested in:
1. How you will determine and trust the incoming IP
1. How you will configure ip ranges per org
1. How you will enforce the access constraints

Have you taken a look at [route services](https://docs.cloudfoundry.org/services/route-services.html) as a possible extension point to add additional policy?

I do wonder if CC is the correct place to apply incoming IP policy, since it is likely behind many layers of proxies -- LB, gorouter, etc.

**Comment by cnelson** [comment]
@zrob 

> Specifically I'm interested in:

1. For our use-case we'd assume we can trust X-Forwarded-For as the CC already does for things like rate-limiting.

2. We were hoping for some feedback from you here on what an acceptable approach would be. I think the right way to do this would be to associate this data with the org via extending `PUT /v2/organizations` or adding a new method to set this information. 

3. We'd expect the CC to return `CF-NotAuthorized` (or another error you deem appropriate) if a request is made that would otherwise be authenticated but comes from a disallowed address.

> Have you taken a look at route services as a possible extension point to add additional policy?

Is it possible to put a route service in front of the CC?  I've only used it for fronting hosted apps, not CF components themselves -- regardless of how you put a proxy in front of the CC it's hard to implement this kind of filtering with one:

> I do wonder if CC is the correct place to apply incoming IP policy, since it is likely behind many layers of proxies -- LB, gorouter, etc.

I'd love to hear your thoughts on how this could be accomplished further up the stack, we came to the conclusion that this belongs in CC as the knowledge of which resource belongs to which organization only exists in CC.  For any proxy to implement this kind of filtering, it would need to understand CAPI at a deep level in order to  properly filter all requests based on which org owns the resource a given request is operating on. For the majority of requests this means parsing the full request (including the body), and then making additional requests to the CC to find out which org owns the resource being queried so the filtering could be applied.   This type of proxy was our initial approach when looking to solve this need, but we abandoned the idea after some research as we felt the complexity involved made it too brittle.

We also considered making this simpler by implementing filtering based on user and not organization as that would only require inspecting the auth info in each request and figuring out who the user is but users can be members of multiple organizations some of which may have ip filtering policies enabled while others may not.  We felt it could be potentially very confusing for a user when their request for something in org b is rejected because they are also a member of org a and it has IP filtering enabled.

Hopefully this helps explain our thought process and research to date on this feature request.

**Comment by mogul** [comment]
Knowing you're open to the idea was the first hurdle. Now that we know that, we'll noodle out some of the details and get back to you here soon.

We did consider route services, but those are only applicable for app traffic, not the API. Unless we're missing something?

**Comment by mogul** [comment]
(Oh whoops, GitHub hadn't updated so I'm only now seeing @cnelson's post.)

**Comment by cnelson** [comment]
@zrob -- Wondering if you've had a chance to read / think about this any more?  We are scheduling work for the next quarter and are trying to decide if we should allocate some time in our schedule for working on a PR for this feature.

**Comment by cnelson** [comment]
@zrob  Checking in again.  Have you had a chance to review the answers to your questions?

**Comment by mogul** [comment]
Following discussion with @zrob yesterday, it seems like there's low appetite for CAPI taking on a role involving trusting `X-Forwarded-For` headers, and in general doing IP-related things at the CAPI level. 

So we've decided to implement a different feature which is less flexible and self-service, but can be implemented outside CAPI in a proxy: 

0. For certain (e-mail) domains, we will (manually) collect the set of expected IP ranges for users in that domain.
1. In each request to CAPI, we'll inspect the auth info and figure out which (e-mail) domain the user belongs to. 
2. If we have a whitelist of IP ranges on record for that domain, and the request didn't come from one of them, we'll return `403 Forbidden`. Otherwise we'll pass it through.

@zrob you mentioned you thought it was possible to put a route-service in front of CAPI. Can you point out documentation or a sample showing how to accomplish this?

There's a CAPI feature request here, though it's not needed for us to proceed: We'd like a simple, consistent way to query CAPI for the org and space associated with a particular resource, across all resource types. If that existed, it would make writing features like this a lot easier... There'd be no need to modify CAPI directly and we wouldn't be stuck writing brittle API-aware filtering code, and we would be able to implement this kind of policy at the org- rather than user/domain-level, as we'd intended.

**Comment by mogul** [comment]
> We'd like a simple, consistent way to query CAPI for the org and space associated with a particular resource, across all resource types. 

Even better if we can also find out the isolation segment... Then it's easy to also have the proxy enforce policy relative only to specific segments.

**Comment by mogul** [comment]
Any thoughts about this?

> We'd like a simple, consistent way to query CAPI for the org and space associated with a particular resource, across all resource types. If that existed, it would make writing features like this a lot easier... There'd be no need to modify CAPI directly and we wouldn't be stuck writing brittle API-aware filtering code, and we would be able to implement this kind of policy at the org- rather than user/domain-level, as we'd intended. 

Would you be open to accepting a PR that refactors and consolidates that logic, with the expectation it could be exposed via an API addition (or factored out into a separate service, if that makes sense)?

**Comment by zrob** [comment]
Was able to discuss this out of band with @mogul.

We agreed that CC was not a good option for handling IP based policy.
