### ISSUE TITLE
/v2/events filtering by timestamp using ">" not working as expected

### ISSUE THREAD

**Issue by MitchK** [cloudfoundry/cloud_controller_ng#849]
## Issue

I want to filter events by a timestamp. When I ever do 

```
GET https://api-endpoint/v2/events?order-by=timestamp&order-direction=desc&results-per-page=100&q=timestamp>2017-07-11T23:08:22Z
```

it returns events including that timestamp, not excluding the timestamp. 

## Context

I want to get the latest events since a certain time stamp. 

API version of Cloud Foundry installation is 2.84.0.

## Steps to Reproduce

1. Take timestamp of latest event
2. Perform this request I want to filter events by a timestamp: ```GET https://api-endpoint/v2/events?order-by=timestamp&order-direction=desc&results-per-page=100&q=timestamp>TIMESTAMP```

3. It will include events with that time stamp.

## Expected result

For the latest timestamp, it should return no events at all.

## Current result

For the latest timestamp, it currently returns all events with that time stamp

## Possible Fix

--

## screenshot

--

**Comment by Gerg** [comment]
Hey @MitchK,

I was able to reproduce this issue. This is caused because postgres stores datetimes with higher precision than we present on the API. When we retrieve the events from the cloud controller's database more recent than `2017-07-11T23:08:22Z`, we will include events that happened at `2017-07-11T23:08:22.XXXXXXZ` for XXXXXX > 000000. You can verify this by sending a more precise query and looking at the results (for example: `q=timestamp>2017-07-11T23:08:22.5Z`).

I agree that this behavior is confusing for API users. I'll throw this over to our PM @zrob to determine if and how we want to alter this behavior. In the meanwhile, you can get the behavior you are looking for by using the query `q=timestamp>2017-07-11T23:08:22.999999Z`.

Thanks,
@gerg

**Comment by ericpromislow** [comment]
We've fixed this by modifying timestamp-related queries to take into account that values stored in the database are not always presented the same way. 

Eric Promislow and Annie Sing, CAPI Community Pair
