### ISSUE TITLE
Buildpack / Stack association

### ISSUE THREAD

**Issue by dgodd** [cloudfoundry/cloud_controller_ng#860]
## Issue

We would like to associate a stack with a buildpack. This would mean that we could have multiple buildpacks with the same name, and provide to a cell only those which match its stack. This enables a smooth path for users to migrate from cflinuxfs2 to cflinuxfs3. As a side benefit this also improves both performance and UX for windows buildpacks.

## Context

This Issue includes a discussion of what we would like to do as a PR, we hope to start discussion and flesh out any issues before starting the work on the PR.

## Possible Fix

We have implemented a pseudo code set of changes on https://github.com/dgodd/cloud_controller_ng/commit/61f2a7892a498d1edd1f42230bb655000fb4305a. Note this commit will not run, but was hoped to be useful as part of the discussion of our intent.

1. Each buildpack must have one stack associated with it
1. When a buildpack is uploaded, the stack will be determined from the zip file
1. When finding buildpacks for staging, only select buildpacks for that stack

### Error Handling (not part of pseudo code commit):

1. When updating or deleting a buildpack, verify that a stack was provided if there are more than one with the same name. This would require a change to the cli to allow specifying a stack on update and delete commands (and plausibly verifying the same buildpack+stack behavior)
1. If an update is peformed when specifying stack `A` and the buildpack bits specify stack `B` refuse the update. This may require changing the order of cli's update requests (i.e. update bits before updating properties)
1. Error messages for users need to be changed. For instance, if a user requests a system buildpack+stack combination which does not exist, we suspect the current error message will be confusing (this is mostly in the context of multi buildpacks). 

We are happy to discuss these changes any time that suits, provided it is during US EST work time.

**Comment by ljfranklin** [comment]
@dgodd From the engineering side I'm curious about the specifics of `extract_stack_from_buildpack`. Is there a yml file in the root of the zip that we'll need to extract and parse? There's also some interesting performance implications due to Ruby being bad at doing stuff concurrently. We typically do all file processing and uploading in a background job so it doesn't block an entire ruby process, but it looks like uploading buildpacks via the CLI doesn't take place in a background job. Any unzipping would only make this worse. Maybe we should revisit doing the buildpack handling in a background job.

Also sounds like `stack` will be a required field on buildpacks going forward with this plan. What should the `stack` value be for all existing buildpacks?

@zrob does this change sound reasonable from the product side?

**Comment by dgodd** [comment]
@ljfranklin 

Re: default stack: CF has a default stack, so thought that the existing buildpacks would be set to that.

Re: extract_stack_from_buildpack: Yes, that would need to be determined from the manifest.yml file inside the buildpack zip. 

A similar extraction (language) could be done today using
```bash
unzip -p dotnet-core_buildpack-cached-v1.0.25-1504722452.zip manifest.yml | ruby -r 'yaml' -e 'puts YAML.load(STDIN.read).dig("language")'
```
or
```ruby
YAML.load(`unzip -p dotnet-core_buildpack-v1.0.25.zip manifest.yml`).dig("language")
```
and is pretty fast even on large buildpacks

**Comment by sclevine** [comment]
@ljfranklin @zrob @tcdowney We're going to start working on this PR soon: https://www.pivotaltracker.com/story/show/153256959

Any objections?

**Comment by zrob** [comment]
this work has completed
