### ISSUE TITLE
Create new role (space|org)_operator

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cloud_controller_ng#873]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Currently there seem to be no way to assign limited privileges to (L1-style) operators.

## Context

Our internal users often have L1 operators that perform basic troubleshooting duties. It would help them embark them on the devops journey to have such a role available. For this role they need the following privileges in addition to the (space|org)_auditor privileges:

- see application logs
- restart instances
- (ideally) change number of instances
- (ideally) ssh in

What they explicitly don't need:

- push/update/delete/start/stop applications
- modify applications (except for the number of instances)
- modify routes
- modify services
- modify env vars

## Possible Fix

There are two main ways to do this:
- (easy) define the two new roles (org_operator and space_operator) and allow (org|space)_managers to assign roles to users
- (hard) allow (org|space)_managers to define roles and which privileges they have, allow (org|space)_managers to assign roles to users

**Comment by CAFxX** [comment]
@xoebus: @shalako mentioned you may be interested in this as a use case for the finegrained authorization work

**Comment by zrob** [comment]
Hi @CAFxX 

Thanks for sharing this use-case.  It sounds like you have been told about the fine-grained auth effort.  That team has formed just this past Monday.  They will hopefully be sharing more info with the community soon.

We will not be adding this role to CC today, but will instead use the result of the fine-grained auth work that the new team is working on to provide this.  I'm going to close this issue since it isn't something we will be doing in CC, but please keep an eye out for info from the new team/component.

/cc @xoebus 

Thanks!
@zrob
