### ISSUE TITLE
API: source code link

### ISSUE THREAD

**Issue by giner** [cloudfoundry/cloud_controller_ng#904]
It would be very convenient to have an optional field for link to source code for a particular application. Something like this:
```
$ cf app myapp
Showing health and status for app myapp in org rpaas / space dev as stas

name:              myapp
requested state:   started
instances:         1/1
usage:             256M x 1 instances
routes:            ...
last uploaded:     ...
stack:             cflinuxfs2
buildpack:         ...
source code:       https://git.domain.com/rpaas/myapp  # <====== HERE

     state     since                  cpu    memory          disk         details
#0   running   2017-09-20T04:58:00Z   0.0%   23.3M of 256M   109M of 1G   
```

If this is implemented cf cli could be changed to detect source code link automatically when possible.

**Comment by Gerg** [comment]
Hey @giner,

Thank you for this suggestion. We are in the early stages of design on an annotations feature similar to [kubernetes' API](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/). Would this meet your needs?

Thanks,
Greg

**Comment by giner** [comment]
Hi @gerg,

It will do. Good to know you are working on this.

**Comment by MFranca** [comment]
Hey @Gerg and @giner ,  I, also, would like to suggest an additional field on the next API version... I hope there is no problem to "get a ride" on this one (#904) since I believe it'similar... But I apologize if it's not the case, and let me know if you want me to open a new one just for my suggestion, will you?... :-)

So, **my suggestion is to add a field, to the Service JSON, that would store the link for the OpenAPI (former Swagger) specification for the service - https://www.openapis.org/.** 

E.g., 
`GET /v2/services`
```
{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "1993218f-096d-4216-bf9d-e0f250332dc6",
        "url": "/v2/services/1993218f-096d-4216-bf9d-e0f250332dc6",
        "created_at": "2016-06-08T16:41:31Z",
        "updated_at": "2016-06-08T16:41:26Z"
      },
      "entity": {
        "label": "label-57",
        "provider": null,
        "url": null,
        "description": "desc-134",
        "long_description": null,
        "version": null,
        "info_url": null,
        "active": true,
        "bindable": true,
        "unique_id": "4ab67d2e-18c0-4a36-8eed-fdee36fdd61b",
        "extra": null,
        "tags": [

        ],
        "requires": [

        ],
        "documentation_url": null,
        "openapi_url": null, # <====== HERE
        "service_broker_guid": "34b94a65-3cd3-4655-8c07-e2bd94ae21c5",
        "plan_updateable": false,
        "service_plans_url": "/v2/services/1993218f-096d-4216-bf9d-e0f250332dc6/service_plans"
      }
    }
  ]
}
```
**Justification**: As far as I understand, differently than "traditional" SOAP/XML webservices that you could just append "?wsdl" to an endpoint to retrieve all method signatures (operations available), for new RESTful services using **Swagger/OpenAPI standard** for documenting purpose, there is no way to automatically discover the url for the specification... :-( So, developers would benefit from knowing where to look for the OpenAPI specification, and applications could dynamically find and consume specific operations...

Ref.: https://apidocs.cloudfoundry.org/272/services/list_all_services.html

**Comment by CAFxX** [comment]
> We are in the early stages of design on an annotations feature similar to kubernetes' API.

A couple of questions since we're on topic then:

- will this work uniformly for all kinds of "objects" (apps, routes, spaces, orgs, services) or only for apps?
- was it considered to control access to the metadata? e.g. I can imagine use cases for at least the following:
  - as operators we could use the ability to attach metadata that only admins can read/write and that only global auditors can read
  - as operators we could use the ability to attach metadata that only admins can read/write and that all users (with read access to the parent object) can read
  - as org/space manager we could use the ability to attach metadata that only org/space managers can read/write and that all users (with read access to the parent object) can read

**Comment by cwlbraa** [comment]
this is scheduled and in progress! you can follow along here: https://www.pivotaltracker.com/story/show/160942050

Apps will be the first resource to support this sort of tagging, but the other resources you've mentioned are planned. It’s also important to note that, on our first pass, this labels+selectors api will NOT have access controls built in that are any different from access controls on the app itself. That means platform engineers & app developers using labels for chargebacks or other auditing will have to rely on an honor system.
