### ISSUE TITLE
syslog entries in nginx.conf.erb spill over /var/log/messages

### ISSUE THREAD

**Issue by hphde** [cloudfoundry/cloud_controller_ng#947]
## Issue
The commit
https://github.com/cloudfoundry/cloud_controller_ng/commit/ccb1985f352de2d56ea1b9e7750049bf8effd1fe#diff-e51e3f1c4756bf8e0e3749771c3527f2
introduced entries to nginx.conf.erb for syslog. This messages end up in `/var/log/messages` and can easily flood fill the root disk.

## Context
What is the rational behind that change @thausler786? Or is there a config option to overwrite this behaviour I didn't find?

## Steps to Reproduce
It's default

## Expected result
Check `/var/log/messages` for entries from nginx

## Possible Fix
Either remove the entries from the nginx.conf(.erb) or filter out tagged messages from syslog

**Comment by Gerg** [comment]
For context, here is the story that sparked this commit: https://www.pivotaltracker.com/story/show/79114924

**Comment by smoser-ibm** [comment]
@Gerg Is there an easy way to turn this off if I don't want this ?

**Comment by smoser-ibm** [comment]
@gerg is there an easy way to turn this off if I don't want this (or at least not the nginx stuff, the other syslog deamon things are OK) ?

**Comment by tcdowney** [comment]
@smoser-ibm there currently isn't a way to disable it. Just curious though, what stemcell version are you on?

Per https://github.com/cloudfoundry/bosh/issues/1418#issuecomment-247738029, `/var/log` should be mounted on the ephemeral disk and shouldn't be filling up your root disk these days.

**Comment by hphde** [comment]
To some degree this is all good and understandable (sending messages to syslog and still have them under the expected jobs location; now `/var/log` has it's own disk). The question for me still is why I need the logs twice on the system? I assume (and still would like to get feedback from @thausler786 or @luan) that syslog messages will still be forwarded to some central place and discarded locally. The change hasn't introduced something like this.

If my assumption is correct IMHO it would make sense to have
- a config option for central syslog
- syslog messages from jobs get's discarded as default to not fill disks (because they are still available under `/var/vcap/sys/log/<job>`)

Examples:

For the first (optional) part it could be done like that
`/etc/rsyslog.d/40-cf-jobs-central-syslog-forward.conf`
```
if $syslogtag == "cf-nginx:" then {
  @@<central-syslog-ip-address>:<port>
}
```

For the second part it must be before `/etc/rsyslog.d/50-default.conf` so like
`/etc/rsyslog.d/49-cf-jobs-default.conf`
```
if $syslogtag == "cf-nginx:" then {
  stop
}
```

These are stubs and by no means complete or fitting to what's currently in the code - just to get the picture.

**Comment by tcdowney** [comment]
@hphde I think the pattern we've been following lately is to stop writing directly to syslog and just write all logs as files on disk in `/var/vcap/sys/log/<job>` (recent example: [#151811590](https://www.pivotaltracker.com/story/show/151811590)). We leave it to the operator to co-locate a syslog forwarder like [syslog-release](https://github.com/cloudfoundry/syslog-release) to forward logs to a remote server.

@zrob should we remove/make it configurable whether nginx writes its access logs directly to syslog?

**Comment by maryamklabib** [comment]
Hello @hphde ,

Are you still seeing this behavior of nginx logs going to `/var/log/messages` on the latest CAPI version? 

It seems this behavior *may* have changed since this issue was filed.

If you are still seeing this behavior, can you provide more details such as:

- How are you deploying your CC?
- What specific steps did you follow to reproduce it?
- What exactly are you observing?

-- @selzoc and maryam

**Comment by hphde** [comment]
The exact lines I claimed above with commit https://github.com/cloudfoundry/cloud_controller_ng/commit/ccb1985f352de2d56ea1b9e7750049bf8effd1fe#diff-e51e3f1c4756bf8e0e3749771c3527f2 are still present in https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/templates/nginx.conf.erb

So without trying - why should it have changed? What's on the syslog side catching and dropping the messages? According to https://www.pivotaltracker.com/n/projects/966314/stories/152139367 others also reproduced the issue.

**Comment by maryamklabib** [comment]
@hphde 
I apologize. I could have communicated our questions and root concerns better. Those lines are indeed still present. We attempted to reproduce the issue. It seems that those lines you called out are not the root cause for this behavior. Adding them does not guarantee reproduction of the issue you stated and removing them does not prevent the nginx logs from still ending up in syslog. We were finding some inconclusive results. [You can see more info about our attempts here](https://www.pivotaltracker.com/story/show/152139367)

You are correct that this was reproduced before. The change that did occur is the [syslog release](https://github.com/cloudfoundry/syslog-release), which complicated the behavior around this when we deployed with it. I was curious if you had started using it, and if you had a clean way to reproduce with it.

I hope this background was helpful. Given all this, could you provide detailed reproduction steps:

- How are you deploying your CC?
- What specific steps did you follow to reproduce it?
- What exactly are you observing?

**Comment by selzoc** [comment]
@hphde, bumping this as we haven't heard from you in 20 days.

Thanks,
Chris && Davis

**Comment by selzoc** [comment]
@hphde Haven't heard from you in a while, so we're going to close this issue.  Please feel free to re-open.

Thanks,
Chris && Davis
