### ISSUE TITLE
v3 droplet copy acceptance test failing for NFS fog

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#949]
## Issue
Running cf-release acceptance tests while upgrading to release 278 I noticed that the v3 droplet copy integration test was failing.

## Context

Here is the error output from the test:

```
[v3] droplet features copying a droplet [It] can copy a droplet
/var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry/cf-acceptance-tests/v3/droplet.go:86

  Saw:
      {
         "guid": "bb2aee32-30ae-4655-bc2d-2ab25429ffb9",
         "state": "FAILED",
         "error": "failed to copy - Permission denied @ rb_sysopen - /var/vcap/nfs/shared/cc-droplets/bb/2a/bb2aee32-30ae-4655-bc2d-2ab25429ffb9/e1ad2fb40551aad403289e11cddb9f310830364a",
         "lifecycle": {
            "type": "buildpack",
            "data": {}
         },
         "checksum": null,
         "buildpacks": [
            {
               "name": "ruby_buildpack",
               "detect_output": null
            }
         ],
         "stack": "cflinuxfs2",
         "image": null,
         "execution_metadata": "",
         "process_types": {
            "console": "bundle exec irb",
            "rake": "bundle exec rake",
            "web": "bundle exec rackup config.ru -p $PORT",
            "worker": "bundle exec rackup config.ru -p $PORT"
         },
         "created_at": "2017-10-20T20:09:14Z",
         "updated_at": "2017-10-20T20:09:15Z",
         "links": {
            "self": {
               "href": "https://cf.domain/v3/droplets/bb2aee32-30ae-4655-bc2d-2ab25429ffb9"
            },
            "package": null,
            "app": {
               "href": "https://cf.domain/v3/apps/42c742ba-ac85-4c27-872e-26f216923b8a"
            },
            "assign_current_droplet": {
               "href": "https://cf.domain/v3/apps/42c742ba-ac85-4c27-872e-26f216923b8a/relationships/current_droplet",
               "method": "PATCH"
            }
         }
      }

  Which matches the unexpected:
      FAILED

  /var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry/cf-acceptance-tests/helpers/v3_helpers/v3.go:389
```

Checking in my CC the destination droplet is read only.

## Steps to Reproduce

Try to run the v3 droplet copy test against NFS blobstore in cf-release 278

## Expected result

Tests should pass

## Current result

Tests Fail

## Possible Fix

Perhaps droplets need to be made rw similar to the recent staging buildpack fix?

If you cannot duplicate LMK and I'll dig deeper.

**Comment by ljfranklin** [comment]
@youngm We've had a couple reported NFS issues come up recently. We've got a story coming up to get a CI env setup with NFS: https://www.pivotaltracker.com/story/show/150375975. Once that's done we can dig a little deeper into this issue.

**Comment by tcdowney** [comment]
We've been working on getting our permanent CI-ed NFS test environment set up in [#150375975](https://www.pivotaltracker.com/story/show/150375975). While doing that we saw several CATS failures around them and didn't realize that this issue had already been submitted here at the time.

Anyways, we've been working on this particular issue in [#153418863](https://www.pivotaltracker.com/story/show/153418863) and commit https://github.com/cloudfoundry/cloud_controller_ng/commit/dc3ef641964f6488062141d5191440bbdb69cffc should address it. In the case of copying a droplet, having them be read only on the mounted NFS volume is okay because we're just reading an existing droplet and copying it over to create a brand new droplet. The reason why this endpoint was failing was due to the `save` [in these lines](https://github.com/cloudfoundry/cloud_controller_ng/blob/24700c6cb73951bf2e916492064aa5145aca6ffd/lib/cloud_controller/blobstore/fog/fog_client.rb#L91-L95). Setting `public` on a `fog-local File` [doesn't actually do anything](https://github.com/fog/fog-local/blob/46e7a72bc19d0273e216b2986ded6e45ddd60f11/lib/fog/storage/local/models/file.rb#L69-L71) so we could safely omit it and the call to `save`.

Just as a heads up, we've also got another story around NFS CATS failures [in flight](https://www.pivotaltracker.com/story/show/153418205) and a PR to the CATS themselves https://github.com/cloudfoundry/cf-acceptance-tests/pull/257.

Thanks for reporting this @youngm!

**Comment by youngm** [comment]
Thanks @tcdowney I'm really excited you now how a CIed NFS test environment.  This is great.
